description: >-
  Provides operations to manage the reportSettings property of the
  microsoft.graph.admin entity.
get:
  tags:
    - admin.adminReportSettings
  summary: Get adminReportSettings
  description: Get the tenant-level settings for Microsoft 365 reports.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/adminreportsettings-get?view=graph-rest-1.0
  operationId: admin.GetReportSettings
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.adminReportSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - admin.adminReportSettings
  summary: Update adminReportSettings
  description: Update tenant-level settings for Microsoft 365 reports.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/adminreportsettings-update?view=graph-rest-1.0
  operationId: admin.UpdateReportSettings
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.adminReportSettings.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.adminReportSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - admin.adminReportSettings
  summary: Delete navigation property reportSettings for admin
  operationId: admin.DeleteReportSettings
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
