description: >-
  Provides operations to manage the federatedIdentityCredentials property of the
  microsoft.graph.application entity.
get:
  tags:
    - applications.federatedIdentityCredential
  summary: Get federatedIdentityCredential
  description: >-
    Read the properties and relationships of a federatedIdentityCredential
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/federatedidentitycredential-get?view=graph-rest-1.0
  operationId: applications.GetFederatedIdentityCredentials
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.federatedIdentityCredential.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - applications.federatedIdentityCredential
  summary: Upsert federatedIdentityCredential
  description: >-
    Create a new federatedIdentityCredential object for an application if it
    doesn't exist, or update the properties of an existing
    federatedIdentityCredential object. By configuring a trust relationship
    between your Microsoft Entra application registration and the identity
    provider for your compute platform, you can use tokens issued by that
    platform to authenticate with Microsoft identity platform and call APIs in
    the Microsoft ecosystem. Maximum of 20 objects can be added to an
    application.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/federatedidentitycredential-upsert?view=graph-rest-1.0
  operationId: applications.UpdateFederatedIdentityCredentials
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.federatedIdentityCredential.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.federatedIdentityCredential.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - applications.federatedIdentityCredential
  summary: Delete federatedIdentityCredential
  description: Delete a federatedIdentityCredential object from an application.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0
  operationId: applications.DeleteFederatedIdentityCredentials
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: federatedIdentityCredential-id
    in: path
    description: The unique identifier of federatedIdentityCredential
    required: true
    schema:
      type: string
    x-ms-docs-key-type: federatedIdentityCredential
x-ms-docs-grouped-path:
  - /applications/{application-id}/federatedIdentityCredentials(name='{name}')
