description: >-
  Provides operations to manage the extensionProperties property of the
  microsoft.graph.application entity.
get:
  tags:
    - applications.extensionProperty
  summary: Get extensionProperty (directory extension)
  description: >-
    Read a directory extension definition represented by an extensionProperty
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/extensionproperty-get?view=graph-rest-1.0
  operationId: applications.GetExtensionProperties
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.extensionProperty.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - applications.extensionProperty
  summary: Update the navigation property extensionProperties in applications
  operationId: applications.UpdateExtensionProperties
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.extensionProperty.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.extensionProperty.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - applications.extensionProperty
  summary: Delete extensionProperty (directory extension)
  description: >-
    Delete a directory extension definition represented by an extensionProperty
    object. You can delete only directory extensions that aren't synced from
    on-premises active directory (AD).
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/extensionproperty-delete?view=graph-rest-1.0
  operationId: applications.DeleteExtensionProperties
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: extensionProperty-id
    in: path
    description: The unique identifier of extensionProperty
    required: true
    schema:
      type: string
    x-ms-docs-key-type: extensionProperty
