description: Provides operations to manage the collection of applicationTemplate entities.
get:
  tags:
    - applicationTemplates.applicationTemplate
  summary: Get applicationTemplate
  description: Retrieve the properties of an applicationTemplate object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/applicationtemplate-get?view=graph-rest-1.0
  operationId: applicationTemplates.applicationTemplate.GetApplicationTemplate
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved entity
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.applicationTemplate.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: applicationTemplate-id
    in: path
    description: The unique identifier of applicationTemplate
    required: true
    schema:
      type: string
    x-ms-docs-key-type: applicationTemplate
