description: Provides operations to call the acquireAccessToken method.
post:
  tags:
    - applications.synchronization
  summary: Invoke action acquireAccessToken
  description: >-
    Acquire an OAuth access token to authorize the Microsoft Entra provisioning
    service to provision users into an application.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/synchronization-synchronization-acquireaccesstoken?view=graph-rest-1.0
  operationId: applications.application.synchronization.acquireAccessToken
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            credentials:
              type: array
              items:
                $ref: >-
                  ..\components\schemas\microsoft.graph.synchronizationSecretKeyStringValuePair.yaml
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
