description: Provides operations to manage the collection of application entities.
get:
  tags:
    - applications.application
  summary: List applications
  description: Get the list of applications in this organization.
  externalDocs:
    description: Find more info here
    url: https://learn.microsoft.com/graph/api/application-list?view=graph-rest-1.0
  operationId: applications.application.ListApplication
  parameters:
    - name: ConsistencyLevel
      in: header
      description: >-
        Indicates the requested consistency level. Documentation URL:
        https://docs.microsoft.com/graph/aad-advanced-queries
      schema:
        type: string
      examples:
        example-1:
          description: >-
            $search and $count queries require the client to set the
            ConsistencyLevel HTTP header to 'eventual'.
          value: eventual
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.applicationCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - applications.application
  summary: Create application
  description: Create a new application object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-post-applications?view=graph-rest-1.0
  operationId: applications.application.CreateApplication
  requestBody:
    description: New entity
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.application.yaml
    required: true
  responses:
    2XX:
      description: Created entity
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.application.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
