description: Provides operations to call the setVerifiedPublisher method.
post:
  tags:
    - applications.application
  summary: Invoke action setVerifiedPublisher
  description: >-
    Set the verifiedPublisher on an application. For more information, including
    prerequisites to setting a verified publisher, see Publisher verification.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-setverifiedpublisher?view=graph-rest-1.0
  operationId: applications.application.setVerifiedPublisher
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            verifiedPublisherId:
              type: string
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
