description: >-
  Provides operations to manage the jobs property of the
  microsoft.graph.synchronization entity.
get:
  tags:
    - applications.synchronization
  summary: Get jobs from applications
  description: >-
    Performs synchronization by periodically running in the background, polling
    for changes in one directory, and pushing them to another directory.
  operationId: applications.synchronization.GetJobs
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.synchronizationJob.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - applications.synchronization
  summary: Update the navigation property jobs in applications
  operationId: applications.synchronization.UpdateJobs
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.synchronizationJob.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.synchronizationJob.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - applications.synchronization
  summary: Delete navigation property jobs for applications
  operationId: applications.synchronization.DeleteJobs
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: synchronizationJob-id
    in: path
    description: The unique identifier of synchronizationJob
    required: true
    schema:
      type: string
    x-ms-docs-key-type: synchronizationJob
