description: >-
  Provides operations to manage the authenticationMethodConfigurations property
  of the microsoft.graph.authenticationMethodsPolicy entity.
get:
  tags:
    - authenticationMethodsPolicy.authenticationMethodConfiguration
  summary: Get authenticationMethodConfigurations from authenticationMethodsPolicy
  description: >-
    Represents the settings for each authentication method. Automatically
    expanded on GET /policies/authenticationMethodsPolicy.
  operationId: authenticationMethodsPolicy.GetAuthenticationMethodConfigurations
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.authenticationMethodConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - authenticationMethodsPolicy.authenticationMethodConfiguration
  summary: >-
    Update the navigation property authenticationMethodConfigurations in
    authenticationMethodsPolicy
  operationId: authenticationMethodsPolicy.UpdateAuthenticationMethodConfigurations
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.authenticationMethodConfiguration.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.authenticationMethodConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - authenticationMethodsPolicy.authenticationMethodConfiguration
  summary: >-
    Delete navigation property authenticationMethodConfigurations for
    authenticationMethodsPolicy
  operationId: authenticationMethodsPolicy.DeleteAuthenticationMethodConfigurations
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: authenticationMethodConfiguration-id
    in: path
    description: The unique identifier of authenticationMethodConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: authenticationMethodConfiguration
