description: Provides operations to count the resources in the collection.
get:
  tags:
    - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
  summary: Get the number of the resource
  operationId: certificateBasedAuthConfiguration.GetCount-e291
  parameters:
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
  responses:
    2XX:
      $ref: ..\components\responses\ODataCountResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
