description: Provides operations to count the resources in the collection.
get:
  tags:
    - deviceManagement.virtualEndpoint
  summary: Get the number of the resource
  operationId: deviceManagement.virtualEndpoint.userSettings.assignments.GetCount-e245
  parameters:
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
  responses:
    2XX:
      $ref: ..\components\responses\ODataCountResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: cloudPcUserSetting-id
    in: path
    description: The unique identifier of cloudPcUserSetting
    required: true
    schema:
      type: string
    x-ms-docs-key-type: cloudPcUserSetting
