description: >-
  Provides operations to manage the deviceSettingStateSummaries property of the
  microsoft.graph.deviceCompliancePolicy entity.
get:
  tags:
    - deviceManagement.deviceCompliancePolicy
  summary: Get deviceSettingStateSummaries from deviceManagement
  description: Compliance Setting State Device Summary
  operationId: deviceManagement.deviceCompliancePolicies.GetDeviceSettingStateSummaries
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.settingStateDeviceSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.deviceCompliancePolicy
  summary: >-
    Update the navigation property deviceSettingStateSummaries in
    deviceManagement
  operationId: deviceManagement.deviceCompliancePolicies.UpdateDeviceSettingStateSummaries
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.settingStateDeviceSummary.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.settingStateDeviceSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.deviceCompliancePolicy
  summary: Delete navigation property deviceSettingStateSummaries for deviceManagement
  operationId: deviceManagement.deviceCompliancePolicies.DeleteDeviceSettingStateSummaries
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: deviceCompliancePolicy-id
    in: path
    description: The unique identifier of deviceCompliancePolicy
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceCompliancePolicy
  - name: settingStateDeviceSummary-id
    in: path
    description: The unique identifier of settingStateDeviceSummary
    required: true
    schema:
      type: string
    x-ms-docs-key-type: settingStateDeviceSummary
