description: >-
  Provides operations to manage the deviceCompliancePolicySettingStateSummaries
  property of the microsoft.graph.deviceManagement entity.
get:
  tags:
    - deviceManagement.deviceCompliancePolicySettingStateSummary
  summary: Get deviceCompliancePolicySettingStateSummary
  description: >-
    Read properties and relationships of the
    deviceCompliancePolicySettingStateSummary object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecompliancepolicysettingstatesummary-get?view=graph-rest-1.0
  operationId: deviceManagement.GetDeviceCompliancePolicySettingStateSummaries
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceCompliancePolicySettingStateSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.deviceCompliancePolicySettingStateSummary
  summary: Update deviceCompliancePolicySettingStateSummary
  description: Update the properties of a deviceCompliancePolicySettingStateSummary object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecompliancepolicysettingstatesummary-update?view=graph-rest-1.0
  operationId: deviceManagement.UpdateDeviceCompliancePolicySettingStateSummaries
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.deviceCompliancePolicySettingStateSummary.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceCompliancePolicySettingStateSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.deviceCompliancePolicySettingStateSummary
  summary: Delete deviceCompliancePolicySettingStateSummary
  description: Deletes a deviceCompliancePolicySettingStateSummary.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecompliancepolicysettingstatesummary-delete?view=graph-rest-1.0
  operationId: deviceManagement.DeleteDeviceCompliancePolicySettingStateSummaries
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: deviceCompliancePolicySettingStateSummary-id
    in: path
    description: The unique identifier of deviceCompliancePolicySettingStateSummary
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceCompliancePolicySettingStateSummary
