description: >-
  Provides operations to manage the assignments property of the
  microsoft.graph.targetedManagedAppConfiguration entity.
get:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Get assignments from deviceAppManagement
  description: >-
    Navigation property to list of inclusion and exclusion groups to which the
    policy is deployed.
  operationId: deviceAppManagement.targetedManagedAppConfigurations.ListAssignments
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.targetedManagedAppPolicyAssignmentCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Create new navigation property to assignments for deviceAppManagement
  operationId: deviceAppManagement.targetedManagedAppConfigurations.CreateAssignments
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.targetedManagedAppPolicyAssignment.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.targetedManagedAppPolicyAssignment.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: targetedManagedAppConfiguration-id
    in: path
    description: The unique identifier of targetedManagedAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: targetedManagedAppConfiguration
