description: >-
  Provides operations to manage the mobileAppConfigurations property of the
  microsoft.graph.deviceAppManagement entity.
get:
  tags:
    - deviceAppManagement.managedDeviceMobileAppConfiguration
  summary: Get iosMobileAppConfiguration
  description: Read properties and relationships of the iosMobileAppConfiguration object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-apps-iosmobileappconfiguration-get?view=graph-rest-1.0
  operationId: deviceAppManagement.GetMobileAppConfigurations
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedDeviceMobileAppConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceAppManagement.managedDeviceMobileAppConfiguration
  summary: Update iosMobileAppConfiguration
  description: Update the properties of a iosMobileAppConfiguration object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-apps-iosmobileappconfiguration-update?view=graph-rest-1.0
  operationId: deviceAppManagement.UpdateMobileAppConfigurations
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.managedDeviceMobileAppConfiguration.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedDeviceMobileAppConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceAppManagement.managedDeviceMobileAppConfiguration
  summary: Delete iosMobileAppConfiguration
  description: Deletes a iosMobileAppConfiguration.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-apps-iosmobileappconfiguration-delete?view=graph-rest-1.0
  operationId: deviceAppManagement.DeleteMobileAppConfigurations
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: managedDeviceMobileAppConfiguration-id
    in: path
    description: The unique identifier of managedDeviceMobileAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: managedDeviceMobileAppConfiguration
