description: >-
  Provides operations to manage the assignments property of the
  microsoft.graph.targetedManagedAppConfiguration entity.
get:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Get assignments from deviceAppManagement
  description: >-
    Navigation property to list of inclusion and exclusion groups to which the
    policy is deployed.
  operationId: deviceAppManagement.targetedManagedAppConfigurations.GetAssignments
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.targetedManagedAppPolicyAssignment.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Update the navigation property assignments in deviceAppManagement
  operationId: deviceAppManagement.targetedManagedAppConfigurations.UpdateAssignments
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.targetedManagedAppPolicyAssignment.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.targetedManagedAppPolicyAssignment.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Delete navigation property assignments for deviceAppManagement
  operationId: deviceAppManagement.targetedManagedAppConfigurations.DeleteAssignments
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: targetedManagedAppConfiguration-id
    in: path
    description: The unique identifier of targetedManagedAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: targetedManagedAppConfiguration
  - name: targetedManagedAppPolicyAssignment-id
    in: path
    description: The unique identifier of targetedManagedAppPolicyAssignment
    required: true
    schema:
      type: string
    x-ms-docs-key-type: targetedManagedAppPolicyAssignment
