description: >-
  Provides operations to manage the conditionalAccessSettings property of the
  microsoft.graph.deviceManagement entity.
get:
  tags:
    - deviceManagement.onPremisesConditionalAccessSettings
  summary: Get onPremisesConditionalAccessSettings
  description: >-
    Read properties and relationships of the onPremisesConditionalAccessSettings
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-onpremisesconditionalaccesssettings-get?view=graph-rest-1.0
  operationId: deviceManagement.GetConditionalAccessSettings
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.onPremisesConditionalAccessSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.onPremisesConditionalAccessSettings
  summary: Update onPremisesConditionalAccessSettings
  description: Update the properties of a onPremisesConditionalAccessSettings object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-onpremisesconditionalaccesssettings-update?view=graph-rest-1.0
  operationId: deviceManagement.UpdateConditionalAccessSettings
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.onPremisesConditionalAccessSettings.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.onPremisesConditionalAccessSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.onPremisesConditionalAccessSettings
  summary: Delete navigation property conditionalAccessSettings for deviceManagement
  operationId: deviceManagement.DeleteConditionalAccessSettings
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
