description: >-
  Provides operations to manage the userSettings property of the
  microsoft.graph.virtualEndpoint entity.
get:
  tags:
    - deviceManagement.virtualEndpoint
  summary: Get cloudPcUserSetting
  description: Read the properties and relationships of a cloudPcUserSetting object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/cloudpcusersetting-get?view=graph-rest-1.0
  operationId: deviceManagement.virtualEndpoint.GetUserSettings
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.cloudPcUserSetting.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.virtualEndpoint
  summary: Update cloudPcUserSetting
  description: Update the properties of a cloudPcUserSetting object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/cloudpcusersetting-update?view=graph-rest-1.0
  operationId: deviceManagement.virtualEndpoint.UpdateUserSettings
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.cloudPcUserSetting.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.cloudPcUserSetting.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.virtualEndpoint
  summary: Delete cloudPcUserSetting
  description: Delete a cloudPcUserSetting object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/cloudpcusersetting-delete?view=graph-rest-1.0
  operationId: deviceManagement.virtualEndpoint.DeleteUserSettings
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: cloudPcUserSetting-id
    in: path
    description: The unique identifier of cloudPcUserSetting
    required: true
    schema:
      type: string
    x-ms-docs-key-type: cloudPcUserSetting
