description: Provides operations to call the setPriority method.
post:
  tags:
    - deviceManagement.deviceEnrollmentConfiguration
  summary: Invoke action setPriority
  description: Not yet documented
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-deviceenrollmentconfiguration-setpriority?view=graph-rest-1.0
  operationId: >-
    deviceManagement.deviceEnrollmentConfigurations.deviceEnrollmentConfiguration.setPriority
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            priority:
              maximum: 2147483647
              minimum: -2147483648
              type: number
              format: int32
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: deviceEnrollmentConfiguration-id
    in: path
    description: The unique identifier of deviceEnrollmentConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceEnrollmentConfiguration
