description: >-
  Provides operations to manage the deviceCompliancePolicySettingStateSummaries
  property of the microsoft.graph.deviceManagement entity.
get:
  tags:
    - deviceManagement.deviceCompliancePolicySettingStateSummary
  summary: List deviceCompliancePolicySettingStateSummaries
  description: >-
    List properties and relationships of the
    deviceCompliancePolicySettingStateSummary objects.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecompliancepolicysettingstatesummary-list?view=graph-rest-1.0
  operationId: deviceManagement.ListDeviceCompliancePolicySettingStateSummaries
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.deviceCompliancePolicySettingStateSummaryCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - deviceManagement.deviceCompliancePolicySettingStateSummary
  summary: Create deviceCompliancePolicySettingStateSummary
  description: Create a new deviceCompliancePolicySettingStateSummary object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecompliancepolicysettingstatesummary-create?view=graph-rest-1.0
  operationId: deviceManagement.CreateDeviceCompliancePolicySettingStateSummaries
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.deviceCompliancePolicySettingStateSummary.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceCompliancePolicySettingStateSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
