description: >-
  Provides operations to manage the assignments property of the
  microsoft.graph.deviceEnrollmentConfiguration entity.
get:
  tags:
    - deviceManagement.deviceEnrollmentConfiguration
  summary: Get enrollmentConfigurationAssignment
  description: >-
    Read properties and relationships of the enrollmentConfigurationAssignment
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-enrollmentconfigurationassignment-get?view=graph-rest-1.0
  operationId: deviceManagement.deviceEnrollmentConfigurations.GetAssignments
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.enrollmentConfigurationAssignment.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.deviceEnrollmentConfiguration
  summary: Update enrollmentConfigurationAssignment
  description: Update the properties of a enrollmentConfigurationAssignment object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-enrollmentconfigurationassignment-update?view=graph-rest-1.0
  operationId: deviceManagement.deviceEnrollmentConfigurations.UpdateAssignments
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.enrollmentConfigurationAssignment.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.enrollmentConfigurationAssignment.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.deviceEnrollmentConfiguration
  summary: Delete enrollmentConfigurationAssignment
  description: Deletes a enrollmentConfigurationAssignment.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-enrollmentconfigurationassignment-delete?view=graph-rest-1.0
  operationId: deviceManagement.deviceEnrollmentConfigurations.DeleteAssignments
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: deviceEnrollmentConfiguration-id
    in: path
    description: The unique identifier of deviceEnrollmentConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceEnrollmentConfiguration
  - name: enrollmentConfigurationAssignment-id
    in: path
    description: The unique identifier of enrollmentConfigurationAssignment
    required: true
    schema:
      type: string
    x-ms-docs-key-type: enrollmentConfigurationAssignment
