description: Provides operations to count the resources in the collection.
get:
  tags:
    - directory.customSecurityAttributeDefinition
  summary: Get the number of the resource
  operationId: directory.customSecurityAttributeDefinitions.allowedValues.GetCount-c982
  parameters:
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
  responses:
    2XX:
      $ref: ..\components\responses\ODataCountResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: customSecurityAttributeDefinition-id
    in: path
    description: The unique identifier of customSecurityAttributeDefinition
    required: true
    schema:
      type: string
    x-ms-docs-key-type: customSecurityAttributeDefinition
