description: >-
  Provides operations to manage the serviceConfigurationRecords property of the
  microsoft.graph.domain entity.
get:
  tags:
    - domains.domainDnsRecord
  summary: Get serviceConfigurationRecords from domains
  description: >-
    DNS records the customer adds to the DNS zone file of the domain before the
    domain can be used by Microsoft Online services. Read-only, Nullable.
    Doesn't support $expand.
  operationId: domains.GetServiceConfigurationRecords
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.domainDnsRecord.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - domains.domainDnsRecord
  summary: Update the navigation property serviceConfigurationRecords in domains
  operationId: domains.UpdateServiceConfigurationRecords
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.domainDnsRecord.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.domainDnsRecord.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - domains.domainDnsRecord
  summary: Delete navigation property serviceConfigurationRecords for domains
  operationId: domains.DeleteServiceConfigurationRecords
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: domain-id
    in: path
    description: The unique identifier of domain
    required: true
    schema:
      type: string
    x-ms-docs-key-type: domain
  - name: domainDnsRecord-id
    in: path
    description: The unique identifier of domainDnsRecord
    required: true
    schema:
      type: string
    x-ms-docs-key-type: domainDnsRecord
