get:
  tags:
    - drives.list
  summary: Get mailboxSettings property value
  description: >-
    Settings for the primary mailbox of the signed-in user. You can get or
    update settings for sending automatic replies to incoming messages, locale,
    and time zone. Returned only on $select.
  operationId: drives.list.lastModifiedByUser.GetMailboxSettings
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Entity result.
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.mailboxSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
patch:
  tags:
    - drives.list
  summary: Update property mailboxSettings value.
  operationId: drives.list.lastModifiedByUser.UpdateMailboxSettings
  requestBody:
    description: New property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.mailboxSettings.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.mailboxSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: drive-id
    in: path
    description: The unique identifier of drive
    required: true
    schema:
      type: string
    x-ms-docs-key-type: drive
