description: >-
  Provides operations to manage the settings property of the
  microsoft.graph.sharepoint entity.
get:
  tags:
    - admin.sharepoint
  summary: Get settings
  description: Get the tenant-level settings for SharePoint and OneDrive.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/sharepointsettings-get?view=graph-rest-1.0
  operationId: admin.sharepoint.GetSettings
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.sharepointSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - admin.sharepoint
  summary: Update settings
  description: Update one or more tenant-level settings for SharePoint and OneDrive.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/sharepointsettings-update?view=graph-rest-1.0
  operationId: admin.sharepoint.UpdateSettings
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.sharepointSettings.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.sharepointSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - admin.sharepoint
  summary: Delete navigation property settings for admin
  operationId: admin.sharepoint.DeleteSettings
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
