description: Provides operations to call the instantiate method.
post:
  tags:
    - applicationTemplates.applicationTemplate
  summary: Invoke action instantiate
  description: >-
    Add an instance of an application from the Microsoft Entra application
    gallery into your directory. For non-gallery apps, use an application
    template with one of the following IDs to configure different single sign-on
    (SSO) modes like SAML SSO and password-based SSO.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/applicationtemplate-instantiate?view=graph-rest-1.0
  operationId: applicationTemplates.applicationTemplate.instantiate
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            displayName:
              type: string
              nullable: true
            serviceManagementReference:
              type: string
              nullable: true
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            anyOf:
              - $ref: >-
                  ..\components\schemas\microsoft.graph.applicationServicePrincipal.yaml
              - type: object
                nullable: true
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: applicationTemplate-id
    in: path
    description: The unique identifier of applicationTemplate
    required: true
    schema:
      type: string
    x-ms-docs-key-type: applicationTemplate
