description: Provides operations to call the filterOperators method.
get:
  tags:
    - applications.synchronization
  summary: Invoke function filterOperators
  description: List all operators supported in the scoping filters.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/synchronization-synchronizationschema-filteroperators?view=graph-rest-1.0
  operationId: >-
    applications.application.synchronization.jobs.synchronizationJob.schema.filterOperators
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            title: Collection of filterOperatorSchema
            type: object
            allOf:
              - $ref: >-
                  ..\components\schemas\BaseCollectionPaginationCountResponse.yaml
              - type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: >-
                        ..\components\schemas\microsoft.graph.filterOperatorSchema.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: function
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: synchronizationJob-id
    in: path
    description: The unique identifier of synchronizationJob
    required: true
    schema:
      type: string
    x-ms-docs-key-type: synchronizationJob
x-ms-docs-grouped-path:
  - >-
    /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema/filterOperators()
