description: Provides operations to manage the collection of application entities.
delete:
  tags:
    - applications.appManagementPolicy
  summary: Remove appliesTo
  description: >-
    Remove an appManagementPolicy policy object from an application or service
    principal object. When you remove the appManagementPolicy, the application
    or service principal adopts the tenant-wide tenantAppManagementPolicy
    setting. 
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/appmanagementpolicy-delete-appliesto?view=graph-rest-1.0
  operationId: applications.appManagementPolicies.DeleteRefAppManagementPolicy
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: appManagementPolicy-id
    in: path
    description: The unique identifier of appManagementPolicy
    required: true
    schema:
      type: string
    x-ms-docs-key-type: appManagementPolicy
