description: >-
  Provides operations to manage the extensionProperties property of the
  microsoft.graph.application entity.
get:
  tags:
    - applications.extensionProperty
  summary: List extensionProperties (directory extensions)
  description: >-
    Retrieve the list of directory extension definitions, represented by
    extensionProperty objects on an application.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-list-extensionproperty?view=graph-rest-1.0
  operationId: applications.ListExtensionProperties
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.extensionPropertyCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - applications.extensionProperty
  summary: Create extensionProperty (directory extension)
  description: >-
    Create a new directory extension definition, represented by an
    extensionProperty object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-post-extensionproperty?view=graph-rest-1.0
  operationId: applications.CreateExtensionProperties
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.extensionProperty.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.extensionProperty.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
