description: Provides operations to call the removeKey method.
post:
  tags:
    - applications.application
  summary: Invoke action removeKey
  description: >-
    Remove a key credential from an application. This method along with addKey
    can be used by an application to automate rolling its expiring keys. As part
    of the request validation for this method, a proof of possession of an
    existing key is verified before the action can be performed.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-removekey?view=graph-rest-1.0
  operationId: applications.application.removeKey
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            keyId:
              pattern: >-
                ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
              type: string
              format: uuid
            proof:
              type: string
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
