description: >-
  Provides operations to manage the directories property of the
  microsoft.graph.synchronizationSchema entity.
get:
  tags:
    - applications.synchronization
  summary: Get directories from applications
  description: Contains the collection of directories and all of their objects.
  operationId: applications.synchronization.templates.schema.ListDirectories
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.directoryDefinitionCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - applications.synchronization
  summary: Create new navigation property to directories for applications
  operationId: applications.synchronization.templates.schema.CreateDirectories
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.directoryDefinition.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.directoryDefinition.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: synchronizationTemplate-id
    in: path
    description: The unique identifier of synchronizationTemplate
    required: true
    schema:
      type: string
    x-ms-docs-key-type: synchronizationTemplate
x-ms-docs-grouped-path:
  - >-
    /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema/directories
