description: >-
  Provides operations to manage the createdOnBehalfOf property of the
  microsoft.graph.application entity.
get:
  tags:
    - applications.directoryObject
  summary: Get createdOnBehalfOf from applications
  description: Supports $filter (/$count eq 0, /$count ne 0). Read-only.
  operationId: applications.GetCreatedOnBehalfOf
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.directoryObject.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
