put:
  tags:
    - applications.synchronization
  summary: Update property secrets value.
  operationId: applications.synchronization.SetSecrets
  requestBody:
    description: New property values
    content:
      application/json:
        schema:
          type: object
          properties:
            value:
              type: array
              items:
                $ref: >-
                  ..\components\schemas\microsoft.graph.synchronizationSecretKeyStringValuePair.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              value:
                type: array
                items:
                  $ref: >-
                    ..\components\schemas\microsoft.graph.synchronizationSecretKeyStringValuePair.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
