description: >-
  Provides operations to manage the templates property of the
  microsoft.graph.synchronization entity.
get:
  tags:
    - applications.synchronization
  summary: Get templates from applications
  description: Preconfigured synchronization settings for a particular application.
  operationId: applications.synchronization.GetTemplates
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.synchronizationTemplate.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - applications.synchronization
  summary: Update synchronizationTemplate
  description: >-
    Update (override) the synchronization template associated with a given
    application.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/synchronization-synchronizationtemplate-update?view=graph-rest-1.0
  operationId: applications.synchronization.UpdateTemplates
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.synchronizationTemplate.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.synchronizationTemplate.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - applications.synchronization
  summary: Delete navigation property templates for applications
  operationId: applications.synchronization.DeleteTemplates
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: synchronizationTemplate-id
    in: path
    description: The unique identifier of synchronizationTemplate
    required: true
    schema:
      type: string
    x-ms-docs-key-type: synchronizationTemplate
