description: Provides operations to manage the media for the application entity.
get:
  tags:
    - applications.application
  summary: Get logo for application from applications
  description: The main logo for the application. Not nullable.
  operationId: applications.application.GetLogo
  responses:
    2XX:
      description: Retrieved media content
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
put:
  tags:
    - applications.application
  summary: Update logo for application in applications
  description: The main logo for the application. Not nullable.
  operationId: applications.application.UpdateLogo
  requestBody:
    description: New media content.
    content:
      application/octet-stream:
        schema:
          type: string
          format: binary
    required: true
  responses:
    2XX:
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
delete:
  tags:
    - applications.application
  summary: Delete logo for application in applications
  description: The main logo for the application. Not nullable.
  operationId: applications.application.DeleteLogo
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
