description: Provides operations to call the pause method.
post:
  tags:
    - applications.synchronization
  summary: Invoke action pause
  description: >-
    Temporarily stop a running synchronization job. All the progress, including
    job state, is persisted, and the job will continue from where it left off
    when a start call is made.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/synchronization-synchronizationjob-pause?view=graph-rest-1.0
  operationId: applications.application.synchronization.jobs.synchronizationJob.pause
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: synchronizationJob-id
    in: path
    description: The unique identifier of synchronizationJob
    required: true
    schema:
      type: string
    x-ms-docs-key-type: synchronizationJob
