description: Provides operations to manage the collection of application entities.
delete:
  tags:
    - applications.tokenIssuancePolicy
  summary: Remove tokenIssuancePolicy
  description: Remove a tokenIssuancePolicy from an application.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-delete-tokenissuancepolicies?view=graph-rest-1.0
  operationId: applications.tokenIssuancePolicies.DeleteRefTokenIssuancePolicy
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: tokenIssuancePolicy-id
    in: path
    description: The unique identifier of tokenIssuancePolicy
    required: true
    schema:
      type: string
    x-ms-docs-key-type: tokenIssuancePolicy
