description: Casts the previous resource to appRoleAssignment.
get:
  tags:
    - applications.directoryObject
  summary: >-
    Get the item of type microsoft.graph.directoryObject as
    microsoft.graph.appRoleAssignment
  operationId: applications.GetOwners.AsAppRoleAssignment
  parameters:
    - name: ConsistencyLevel
      in: header
      description: >-
        Indicates the requested consistency level. Documentation URL:
        https://docs.microsoft.com/graph/aad-advanced-queries
      schema:
        type: string
      examples:
        example-1:
          description: >-
            $search and $count queries require the client to set the
            ConsistencyLevel HTTP header to 'eventual'.
          value: eventual
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Entity result.
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.appRoleAssignment.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: directoryObject-id
    in: path
    description: The unique identifier of directoryObject
    required: true
    schema:
      type: string
    x-ms-docs-key-type: directoryObject
