description: >-
  Provides operations to manage the federatedIdentityCredentials property of the
  microsoft.graph.application entity.
get:
  tags:
    - applications.federatedIdentityCredential
  summary: List federatedIdentityCredentials
  description: Get a list of the federatedIdentityCredential objects and their properties.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0
  operationId: applications.ListFederatedIdentityCredentials
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.federatedIdentityCredentialCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - applications.federatedIdentityCredential
  summary: Create federatedIdentityCredential
  description: >-
    Create a new federatedIdentityCredential object for an application. By
    configuring a trust relationship between your Microsoft Entra application
    registration and the identity provider for your compute platform, you can
    use tokens issued by that platform to authenticate with Microsoft identity
    platform and call APIs in the Microsoft ecosystem. Maximum of 20 objects can
    be added to an application.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0
  operationId: applications.CreateFederatedIdentityCredentials
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.federatedIdentityCredential.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.federatedIdentityCredential.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
