description: Provides operations to manage the collection of application entities.
get:
  tags:
    - applications.appManagementPolicy
  summary: Get ref of appManagementPolicies from applications
  description: The appManagementPolicy applied to this application.
  operationId: applications.ListRefAppManagementPolicies
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: ..\components\responses\StringCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - applications.appManagementPolicy
  summary: Assign appliesTo
  description: >-
    Assign an appManagementPolicy policy object to an application or service
    principal object. The application or service principal adopts this policy
    over the tenant-wide tenantAppManagementPolicy setting. Only one policy
    object can be assigned to an application or service principal.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-1.0
  operationId: applications.CreateRefAppManagementPolicies
  requestBody:
    $ref: ..\components\requestBodies\refPostBody.yaml
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - applications.appManagementPolicy
  summary: Remove appliesTo
  description: >-
    Remove an appManagementPolicy policy object from an application or service
    principal object. When you remove the appManagementPolicy, the application
    or service principal adopts the tenant-wide tenantAppManagementPolicy
    setting. 
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/appmanagementpolicy-delete-appliesto?view=graph-rest-1.0
  operationId: applications.DeleteRefAppManagementPolicies
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
    - name: '@id'
      in: query
      description: The delete Uri
      required: true
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
