description: >-
  Provides operations to manage the homeRealmDiscoveryPolicies property of the
  microsoft.graph.application entity.
get:
  tags:
    - applications.homeRealmDiscoveryPolicy
  summary: Get homeRealmDiscoveryPolicies from applications
  operationId: applications.GetHomeRealmDiscoveryPolicies
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.homeRealmDiscoveryPolicy.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: homeRealmDiscoveryPolicy-id
    in: path
    description: The unique identifier of homeRealmDiscoveryPolicy
    required: true
    schema:
      type: string
    x-ms-docs-key-type: homeRealmDiscoveryPolicy
