description: >-
  Provides operations to manage the synchronization property of the
  microsoft.graph.application entity.
get:
  tags:
    - applications.synchronization
  summary: Get synchronization from applications
  description: >-
    Represents the capability for Microsoft Entra identity synchronization
    through the Microsoft Graph API.
  operationId: applications.GetSynchronization
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.synchronization.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
put:
  tags:
    - applications.synchronization
  summary: Update the navigation property synchronization in applications
  operationId: applications.SetSynchronization
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.synchronization.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.synchronization.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - applications.synchronization
  summary: Delete navigation property synchronization for applications
  operationId: applications.DeleteSynchronization
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
