description: Provides operations to call the validateCredentials method.
post:
  tags:
    - applications.synchronization
  summary: Invoke action validateCredentials
  operationId: applications.application.synchronization.jobs.validateCredentials
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            applicationIdentifier:
              type: string
              nullable: true
            templateId:
              type: string
              nullable: true
            useSavedCredentials:
              type: boolean
              default: false
              nullable: true
            credentials:
              type: array
              items:
                $ref: >-
                  ..\components\schemas\microsoft.graph.synchronizationSecretKeyStringValuePair.yaml
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
x-ms-docs-grouped-path:
  - >-
    /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/validateCredentials
