description: Provides operations to call the addPassword method.
post:
  tags:
    - applications.application
  summary: Invoke action addPassword
  description: >-
    Adds a strong password or secret to an application. You can also add
    passwords while creating the application.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-addpassword?view=graph-rest-1.0
  operationId: applications.application.addPassword
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            passwordCredential:
              anyOf:
                - $ref: >-
                    ..\components\schemas\microsoft.graph.passwordCredential.yaml
                - type: object
                  nullable: true
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.passwordCredential.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
