description: Provides operations to manage the collection of application entities.
get:
  tags:
    - applications.directoryObject
  summary: List owners of an application
  description: Retrieve a list of owners for an application that are directoryObject types.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-list-owners?view=graph-rest-1.0
  operationId: applications.ListRefOwners
  parameters:
    - name: ConsistencyLevel
      in: header
      description: >-
        Indicates the requested consistency level. Documentation URL:
        https://docs.microsoft.com/graph/aad-advanced-queries
      schema:
        type: string
      examples:
        example-1:
          description: >-
            $search and $count queries require the client to set the
            ConsistencyLevel HTTP header to 'eventual'.
          value: eventual
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: ..\components\responses\StringCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - applications.directoryObject
  summary: Add owner
  description: >-
    Add an owner to an application. Currently, only individual users are
    supported as owners of applications.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-post-owners?view=graph-rest-1.0
  operationId: applications.CreateRefOwners
  requestBody:
    $ref: ..\components\requestBodies\refPostBody.yaml
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - applications.directoryObject
  summary: Remove application owner
  description: >-
    Remove an owner from an application. As a recommended best practice, apps
    should have at least two owners.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-delete-owners?view=graph-rest-1.0
  operationId: applications.DeleteRefOwners
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
    - name: '@id'
      in: query
      description: The delete Uri
      required: true
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
