description: Provides operations to call the provisionOnDemand method.
post:
  tags:
    - applications.synchronization
  summary: Invoke action provisionOnDemand
  description: >-
    Select a user and provision the account on-demand. The rate limit for this
    API is 5 requests per 10 seconds.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/synchronization-synchronizationjob-provisionondemand?view=graph-rest-1.0
  operationId: >-
    applications.application.synchronization.jobs.synchronizationJob.provisionOnDemand
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            parameters:
              type: array
              items:
                $ref: >-
                  ..\components\schemas\microsoft.graph.synchronizationJobApplicationParameters.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.stringKeyStringValuePair.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: synchronizationJob-id
    in: path
    description: The unique identifier of synchronizationJob
    required: true
    schema:
      type: string
    x-ms-docs-key-type: synchronizationJob
