description: Provides operations to call the unsetVerifiedPublisher method.
post:
  tags:
    - applications.application
  summary: Invoke action unsetVerifiedPublisher
  description: >-
    Unset the verifiedPublisher previously set on an application, removing all
    verified publisher properties. For more information, see Publisher
    verification.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-unsetverifiedpublisher?view=graph-rest-1.0
  operationId: applications.application.unsetVerifiedPublisher
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
