description: Provides operations to call the addKey method.
post:
  tags:
    - applications.application
  summary: Invoke action addKey
  description: >-
    Add a key credential to an application. This method, along with removeKey
    can be used by an application to automate rolling its expiring keys. As part
    of the request validation for this method, a proof of possession of an
    existing key is verified before the action can be performed.  Applications
    that don’t have any existing valid certificates (no certificates have been
    added yet, or all certificates have expired), won’t be able to use this
    service action. You can use the Update application operation to perform an
    update instead.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/application-addkey?view=graph-rest-1.0
  operationId: applications.application.addKey
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            keyCredential:
              $ref: ..\components\schemas\microsoft.graph.keyCredential.yaml
            passwordCredential:
              anyOf:
                - $ref: >-
                    ..\components\schemas\microsoft.graph.passwordCredential.yaml
                - type: object
                  nullable: true
            proof:
              type: string
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.keyCredential.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
