description: Provides operations to call the start method.
post:
  tags:
    - applications.synchronization
  summary: Invoke action start
  description: >-
    Start an existing synchronization job. If the job is in a paused state, it
    continues processing changes from the point where it was paused. If the job
    is in quarantine, the quarantine status is cleared. Don't create scripts to
    call the start job continuously while it's running because that can cause
    the service to stop running. Use the start job only when the job is
    currently paused or in quarantine. 
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/synchronization-synchronizationjob-start?view=graph-rest-1.0
  operationId: applications.application.synchronization.jobs.synchronizationJob.start
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: synchronizationJob-id
    in: path
    description: The unique identifier of synchronizationJob
    required: true
    schema:
      type: string
    x-ms-docs-key-type: synchronizationJob
