description: >-
  Provides operations to manage the directories property of the
  microsoft.graph.synchronizationSchema entity.
get:
  tags:
    - applications.synchronization
  summary: Get directories from applications
  description: Contains the collection of directories and all of their objects.
  operationId: applications.synchronization.jobs.schema.GetDirectories
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.directoryDefinition.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - applications.synchronization
  summary: Update the navigation property directories in applications
  operationId: applications.synchronization.jobs.schema.UpdateDirectories
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.directoryDefinition.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.directoryDefinition.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - applications.synchronization
  summary: Delete navigation property directories for applications
  operationId: applications.synchronization.jobs.schema.DeleteDirectories
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: application-id
    in: path
    description: The unique identifier of application
    required: true
    schema:
      type: string
    x-ms-docs-key-type: application
  - name: synchronizationJob-id
    in: path
    description: The unique identifier of synchronizationJob
    required: true
    schema:
      type: string
    x-ms-docs-key-type: synchronizationJob
  - name: directoryDefinition-id
    in: path
    description: The unique identifier of directoryDefinition
    required: true
    schema:
      type: string
    x-ms-docs-key-type: directoryDefinition
x-ms-docs-grouped-path:
  - >-
    /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema/directories/{directoryDefinition-id}
