description: >-
  Provides operations to manage the authenticationMethodConfigurations property
  of the microsoft.graph.authenticationMethodsPolicy entity.
get:
  tags:
    - authenticationMethodsPolicy.authenticationMethodConfiguration
  summary: Get authenticationMethodConfigurations from authenticationMethodsPolicy
  description: >-
    Represents the settings for each authentication method. Automatically
    expanded on GET /policies/authenticationMethodsPolicy.
  operationId: authenticationMethodsPolicy.ListAuthenticationMethodConfigurations
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.authenticationMethodConfigurationCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - authenticationMethodsPolicy.authenticationMethodConfiguration
  summary: >-
    Create new navigation property to authenticationMethodConfigurations for
    authenticationMethodsPolicy
  operationId: authenticationMethodsPolicy.CreateAuthenticationMethodConfigurations
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.authenticationMethodConfiguration.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.authenticationMethodConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
