description: >-
  Provides operations to manage the collection of
  certificateBasedAuthConfiguration entities.
get:
  tags:
    - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
  summary: Get entity from certificateBasedAuthConfiguration by key
  operationId: >-
    certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.GetCertificateBasedAuthConfiguration
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved entity
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.certificateBasedAuthConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
  summary: Update entity in certificateBasedAuthConfiguration
  operationId: >-
    certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.UpdateCertificateBasedAuthConfiguration
  requestBody:
    description: New property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.certificateBasedAuthConfiguration.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.certificateBasedAuthConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
  summary: Delete entity from certificateBasedAuthConfiguration
  operationId: >-
    certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.DeleteCertificateBasedAuthConfiguration
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: certificateBasedAuthConfiguration-id
    in: path
    description: The unique identifier of certificateBasedAuthConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: certificateBasedAuthConfiguration
