description: >-
  Provides operations to manage the collection of
  certificateBasedAuthConfiguration entities.
get:
  tags:
    - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
  summary: Get entities from certificateBasedAuthConfiguration
  operationId: >-
    certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.ListCertificateBasedAuthConfiguration
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.certificateBasedAuthConfigurationCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
  summary: Add new entity to certificateBasedAuthConfiguration
  operationId: >-
    certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.CreateCertificateBasedAuthConfiguration
  requestBody:
    description: New entity
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.certificateBasedAuthConfiguration.yaml
    required: true
  responses:
    2XX:
      description: Created entity
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.certificateBasedAuthConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
