description: >-
  Provides operations to manage the userStatuses property of the
  microsoft.graph.managedDeviceMobileAppConfiguration entity.
get:
  tags:
    - deviceAppManagement.managedDeviceMobileAppConfiguration
  summary: Get managedDeviceMobileAppConfigurationUserStatus
  description: >-
    Read properties and relationships of the
    managedDeviceMobileAppConfigurationUserStatus object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-apps-manageddevicemobileappconfigurationuserstatus-get?view=graph-rest-1.0
  operationId: deviceAppManagement.mobileAppConfigurations.GetUserStatuses
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedDeviceMobileAppConfigurationUserStatus.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceAppManagement.managedDeviceMobileAppConfiguration
  summary: Update managedDeviceMobileAppConfigurationUserStatus
  description: >-
    Update the properties of a managedDeviceMobileAppConfigurationUserStatus
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-apps-manageddevicemobileappconfigurationuserstatus-update?view=graph-rest-1.0
  operationId: deviceAppManagement.mobileAppConfigurations.UpdateUserStatuses
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.managedDeviceMobileAppConfigurationUserStatus.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedDeviceMobileAppConfigurationUserStatus.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceAppManagement.managedDeviceMobileAppConfiguration
  summary: Delete managedDeviceMobileAppConfigurationUserStatus
  description: Deletes a managedDeviceMobileAppConfigurationUserStatus.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-apps-manageddevicemobileappconfigurationuserstatus-delete?view=graph-rest-1.0
  operationId: deviceAppManagement.mobileAppConfigurations.DeleteUserStatuses
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: managedDeviceMobileAppConfiguration-id
    in: path
    description: The unique identifier of managedDeviceMobileAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: managedDeviceMobileAppConfiguration
  - name: managedDeviceMobileAppConfigurationUserStatus-id
    in: path
    description: The unique identifier of managedDeviceMobileAppConfigurationUserStatus
    required: true
    schema:
      type: string
    x-ms-docs-key-type: managedDeviceMobileAppConfigurationUserStatus
