description: >-
  Provides operations to manage the scheduledActionConfigurations property of
  the microsoft.graph.deviceComplianceScheduledActionForRule entity.
get:
  tags:
    - deviceManagement.deviceCompliancePolicy
  summary: List deviceComplianceActionItems
  description: List properties and relationships of the deviceComplianceActionItem objects.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecomplianceactionitem-list?view=graph-rest-1.0
  operationId: >-
    deviceManagement.deviceCompliancePolicies.scheduledActionsForRule.ListScheduledActionConfigurations
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.deviceComplianceActionItemCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - deviceManagement.deviceCompliancePolicy
  summary: Create deviceComplianceActionItem
  description: Create a new deviceComplianceActionItem object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecomplianceactionitem-create?view=graph-rest-1.0
  operationId: >-
    deviceManagement.deviceCompliancePolicies.scheduledActionsForRule.CreateScheduledActionConfigurations
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.deviceComplianceActionItem.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceComplianceActionItem.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: deviceCompliancePolicy-id
    in: path
    description: The unique identifier of deviceCompliancePolicy
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceCompliancePolicy
  - name: deviceComplianceScheduledActionForRule-id
    in: path
    description: The unique identifier of deviceComplianceScheduledActionForRule
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceComplianceScheduledActionForRule
