description: >-
  Provides operations to manage the
  userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
  property of the microsoft.graph.deviceManagement entity.
get:
  tags:
    - >-
      deviceManagement.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
  summary: >-
    Get
    userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
    from deviceManagement
  description: >-
    User experience analytics appHealth Application Performance by App Version
    details
  operationId: >-
    deviceManagement.GetUserExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - >-
      deviceManagement.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
  summary: >-
    Update the navigation property
    userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails in
    deviceManagement
  operationId: >-
    deviceManagement.UpdateUserExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - >-
      deviceManagement.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
  summary: >-
    Delete navigation property
    userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
    for deviceManagement
  operationId: >-
    deviceManagement.DeleteUserExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails-id
    in: path
    description: >-
      The unique identifier of
      userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
    required: true
    schema:
      type: string
    x-ms-docs-key-type: userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
