description: >-
  Provides operations to manage the metricValues property of the
  microsoft.graph.userExperienceAnalyticsCategory entity.
get:
  tags:
    - deviceManagement.userExperienceAnalyticsCategory
  summary: Get metricValues from deviceManagement
  description: The metric values for the user experience analytics category. Read-only.
  operationId: deviceManagement.userExperienceAnalyticsAppHealthOverview.GetMetricValues
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.userExperienceAnalyticsMetric.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.userExperienceAnalyticsCategory
  summary: Update the navigation property metricValues in deviceManagement
  operationId: deviceManagement.userExperienceAnalyticsAppHealthOverview.UpdateMetricValues
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.userExperienceAnalyticsMetric.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.userExperienceAnalyticsMetric.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.userExperienceAnalyticsCategory
  summary: Delete navigation property metricValues for deviceManagement
  operationId: deviceManagement.userExperienceAnalyticsAppHealthOverview.DeleteMetricValues
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: userExperienceAnalyticsMetric-id
    in: path
    description: The unique identifier of userExperienceAnalyticsMetric
    required: true
    schema:
      type: string
    x-ms-docs-key-type: userExperienceAnalyticsMetric
x-ms-docs-grouped-path:
  - >-
    /deviceManagement/userExperienceAnalyticsCategories/{userExperienceAnalyticsCategory-id}/metricValues/{userExperienceAnalyticsMetric-id}
