description: >-
  Provides operations to manage the apps property of the
  microsoft.graph.targetedManagedAppConfiguration entity.
get:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Get apps from deviceAppManagement
  description: List of apps to which the policy is deployed.
  operationId: deviceAppManagement.targetedManagedAppConfigurations.GetApps
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.managedMobileApp.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Update the navigation property apps in deviceAppManagement
  operationId: deviceAppManagement.targetedManagedAppConfigurations.UpdateApps
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.managedMobileApp.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.managedMobileApp.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Delete navigation property apps for deviceAppManagement
  operationId: deviceAppManagement.targetedManagedAppConfigurations.DeleteApps
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: targetedManagedAppConfiguration-id
    in: path
    description: The unique identifier of targetedManagedAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: targetedManagedAppConfiguration
  - name: managedMobileApp-id
    in: path
    description: The unique identifier of managedMobileApp
    required: true
    schema:
      type: string
    x-ms-docs-key-type: managedMobileApp
