description: Provides operations to call the assign method.
post:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Invoke action assign
  description: Not yet documented
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-mam-targetedmanagedappconfiguration-assign?view=graph-rest-1.0
  operationId: >-
    deviceAppManagement.targetedManagedAppConfigurations.targetedManagedAppConfiguration.assign
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            assignments:
              type: array
              items:
                $ref: >-
                  ..\components\schemas\microsoft.graph.targetedManagedAppPolicyAssignment.yaml
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: targetedManagedAppConfiguration-id
    in: path
    description: The unique identifier of targetedManagedAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: targetedManagedAppConfiguration
x-ms-docs-grouped-path:
  - /deviceAppManagement/managedEBooks/{managedEBook-id}/assign
  - >-
    /deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/assign
  - /deviceAppManagement/mobileApps/{mobileApp-id}/assign
