description: >-
  Provides operations to manage the deviceEnrollmentConfigurations property of
  the microsoft.graph.deviceManagement entity.
get:
  tags:
    - deviceManagement.deviceEnrollmentConfiguration
  summary: Get deviceEnrollmentLimitConfiguration
  description: >-
    Read properties and relationships of the deviceEnrollmentLimitConfiguration
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-deviceenrollmentlimitconfiguration-get?view=graph-rest-1.0
  operationId: deviceManagement.GetDeviceEnrollmentConfigurations
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceEnrollmentConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.deviceEnrollmentConfiguration
  summary: Update deviceEnrollmentWindowsHelloForBusinessConfiguration
  description: >-
    Update the properties of a
    deviceEnrollmentWindowsHelloForBusinessConfiguration object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-deviceenrollmentwindowshelloforbusinessconfiguration-update?view=graph-rest-1.0
  operationId: deviceManagement.UpdateDeviceEnrollmentConfigurations
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.deviceEnrollmentConfiguration.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceEnrollmentConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.deviceEnrollmentConfiguration
  summary: Delete deviceEnrollmentPlatformRestrictionsConfiguration
  description: Deletes a deviceEnrollmentPlatformRestrictionsConfiguration.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-onboarding-deviceenrollmentplatformrestrictionsconfiguration-delete?view=graph-rest-1.0
  operationId: deviceManagement.DeleteDeviceEnrollmentConfigurations
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: deviceEnrollmentConfiguration-id
    in: path
    description: The unique identifier of deviceEnrollmentConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceEnrollmentConfiguration
