description: Provides operations to call the assign method.
post:
  tags:
    - deviceManagement.virtualEndpoint
  summary: Invoke action assign
  description: Assign a cloudPcUserSetting to user groups.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/cloudpcusersetting-assign?view=graph-rest-1.0
  operationId: deviceManagement.virtualEndpoint.userSettings.cloudPcUserSetting.assign
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            assignments:
              type: array
              items:
                $ref: >-
                  ..\components\schemas\microsoft.graph.cloudPcUserSettingAssignment.yaml
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: cloudPcUserSetting-id
    in: path
    description: The unique identifier of cloudPcUserSetting
    required: true
    schema:
      type: string
    x-ms-docs-key-type: cloudPcUserSetting
x-ms-docs-grouped-path:
  - >-
    /deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/assign
  - /deviceManagement/deviceConfigurations/{deviceConfiguration-id}/assign
  - >-
    /deviceManagement/deviceEnrollmentConfigurations/{deviceEnrollmentConfiguration-id}/assign
  - >-
    /deviceManagement/virtualEndpoint/provisioningPolicies/{cloudPcProvisioningPolicy-id}/assign
