description: >-
  Provides operations to manage the
  userExperienceAnalyticsAppHealthApplicationPerformance property of the
  microsoft.graph.deviceManagement entity.
get:
  tags:
    - deviceManagement.userExperienceAnalyticsAppHealthApplicationPerformance
  summary: >-
    Get userExperienceAnalyticsAppHealthApplicationPerformance from
    deviceManagement
  description: User experience analytics appHealth Application Performance
  operationId: deviceManagement.GetUserExperienceAnalyticsAppHealthApplicationPerformance
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.userExperienceAnalyticsAppHealthApplicationPerformance.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.userExperienceAnalyticsAppHealthApplicationPerformance
  summary: >-
    Update the navigation property
    userExperienceAnalyticsAppHealthApplicationPerformance in deviceManagement
  operationId: >-
    deviceManagement.UpdateUserExperienceAnalyticsAppHealthApplicationPerformance
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.userExperienceAnalyticsAppHealthApplicationPerformance.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.userExperienceAnalyticsAppHealthApplicationPerformance.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.userExperienceAnalyticsAppHealthApplicationPerformance
  summary: >-
    Delete navigation property
    userExperienceAnalyticsAppHealthApplicationPerformance for deviceManagement
  operationId: >-
    deviceManagement.DeleteUserExperienceAnalyticsAppHealthApplicationPerformance
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: userExperienceAnalyticsAppHealthApplicationPerformance-id
    in: path
    description: >-
      The unique identifier of
      userExperienceAnalyticsAppHealthApplicationPerformance
    required: true
    schema:
      type: string
    x-ms-docs-key-type: userExperienceAnalyticsAppHealthApplicationPerformance
