description: Provides operations to count the resources in the collection.
get:
  tags:
    - deviceManagement.userExperienceAnalyticsAppHealthApplicationPerformance
  summary: Get the number of the resource
  operationId: >-
    deviceManagement.userExperienceAnalyticsAppHealthApplicationPerformance.GetCount-6ac7
  parameters:
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
  responses:
    2XX:
      $ref: ..\components\responses\ODataCountResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
