description: >-
  Provides operations to manage the deploymentSummary property of the
  microsoft.graph.iosManagedAppProtection entity.
get:
  tags:
    - deviceAppManagement.iosManagedAppProtection
  summary: Get managedAppPolicyDeploymentSummary
  description: >-
    Read properties and relationships of the managedAppPolicyDeploymentSummary
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-mam-managedapppolicydeploymentsummary-get?view=graph-rest-1.0
  operationId: deviceAppManagement.iosManagedAppProtections.GetDeploymentSummary
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedAppPolicyDeploymentSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceAppManagement.iosManagedAppProtection
  summary: Update managedAppPolicyDeploymentSummary
  description: Update the properties of a managedAppPolicyDeploymentSummary object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-mam-managedapppolicydeploymentsummary-update?view=graph-rest-1.0
  operationId: deviceAppManagement.iosManagedAppProtections.UpdateDeploymentSummary
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.managedAppPolicyDeploymentSummary.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedAppPolicyDeploymentSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceAppManagement.iosManagedAppProtection
  summary: Delete navigation property deploymentSummary for deviceAppManagement
  operationId: deviceAppManagement.iosManagedAppProtections.DeleteDeploymentSummary
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: iosManagedAppProtection-id
    in: path
    description: The unique identifier of iosManagedAppProtection
    required: true
    schema:
      type: string
    x-ms-docs-key-type: iosManagedAppProtection
