description: >-
  Provides operations to manage the assignments property of the
  microsoft.graph.managedDeviceMobileAppConfiguration entity.
get:
  tags:
    - deviceAppManagement.managedDeviceMobileAppConfiguration
  summary: List managedDeviceMobileAppConfigurationAssignments
  description: >-
    List properties and relationships of the
    managedDeviceMobileAppConfigurationAssignment objects.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-apps-manageddevicemobileappconfigurationassignment-list?view=graph-rest-1.0
  operationId: deviceAppManagement.mobileAppConfigurations.ListAssignments
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.managedDeviceMobileAppConfigurationAssignmentCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - deviceAppManagement.managedDeviceMobileAppConfiguration
  summary: Create managedDeviceMobileAppConfigurationAssignment
  description: Create a new managedDeviceMobileAppConfigurationAssignment object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-apps-manageddevicemobileappconfigurationassignment-create?view=graph-rest-1.0
  operationId: deviceAppManagement.mobileAppConfigurations.CreateAssignments
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.managedDeviceMobileAppConfigurationAssignment.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedDeviceMobileAppConfigurationAssignment.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: managedDeviceMobileAppConfiguration-id
    in: path
    description: The unique identifier of managedDeviceMobileAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: managedDeviceMobileAppConfiguration
