description: Provides operations to call the targetApps method.
post:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Invoke action targetApps
  description: Not yet documented
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-mam-targetedmanagedappconfiguration-targetapps?view=graph-rest-1.0
  operationId: >-
    deviceAppManagement.targetedManagedAppConfigurations.targetedManagedAppConfiguration.targetApps
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            apps:
              type: array
              items:
                $ref: ..\components\schemas\microsoft.graph.managedMobileApp.yaml
            appGroupType:
              anyOf:
                - $ref: >-
                    ..\components\schemas\microsoft.graph.targetedManagedAppGroupType.yaml
                - type: object
                  nullable: true
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: targetedManagedAppConfiguration-id
    in: path
    description: The unique identifier of targetedManagedAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: targetedManagedAppConfiguration
x-ms-docs-grouped-path:
  - /deviceAppManagement/managedAppPolicies/{managedAppPolicy-id}/targetApps
  - >-
    /deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/appliedPolicies/{managedAppPolicy-id}/targetApps
  - >-
    /deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/intendedPolicies/{managedAppPolicy-id}/targetApps
