description: >-
  Provides operations to manage the
  userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
  property of the microsoft.graph.deviceManagement entity.
get:
  tags:
    - >-
      deviceManagement.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
  summary: >-
    Get
    userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
    from deviceManagement
  description: >-
    User experience analytics appHealth Application Performance by App Version
    details
  operationId: >-
    deviceManagement.ListUserExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - >-
      deviceManagement.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
  summary: >-
    Create new navigation property to
    userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
    for deviceManagement
  operationId: >-
    deviceManagement.CreateUserExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
