description: Provides operations to count the resources in the collection.
get:
  tags:
    - deviceManagement.userExperienceAnalyticsCategory
  summary: Get the number of the resource
  operationId: >-
    deviceManagement.userExperienceAnalyticsCategories.metricValues.GetCount-a34c
  parameters:
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
  responses:
    2XX:
      $ref: ..\components\responses\ODataCountResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: userExperienceAnalyticsCategory-id
    in: path
    description: The unique identifier of userExperienceAnalyticsCategory
    required: true
    schema:
      type: string
    x-ms-docs-key-type: userExperienceAnalyticsCategory
