description: >-
  Provides operations to manage the targetedManagedAppConfigurations property of
  the microsoft.graph.deviceAppManagement entity.
get:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Get targetedManagedAppConfiguration
  description: >-
    Read properties and relationships of the targetedManagedAppConfiguration
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-mam-targetedmanagedappconfiguration-get?view=graph-rest-1.0
  operationId: deviceAppManagement.GetTargetedManagedAppConfigurations
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.targetedManagedAppConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Update targetedManagedAppConfiguration
  description: Update the properties of a targetedManagedAppConfiguration object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-mam-targetedmanagedappconfiguration-update?view=graph-rest-1.0
  operationId: deviceAppManagement.UpdateTargetedManagedAppConfigurations
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.targetedManagedAppConfiguration.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.targetedManagedAppConfiguration.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Delete targetedManagedAppConfiguration
  description: Deletes a targetedManagedAppConfiguration.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-mam-targetedmanagedappconfiguration-delete?view=graph-rest-1.0
  operationId: deviceAppManagement.DeleteTargetedManagedAppConfigurations
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: targetedManagedAppConfiguration-id
    in: path
    description: The unique identifier of targetedManagedAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: targetedManagedAppConfiguration
