description: >-
  Provides operations to manage the deploymentSummary property of the
  microsoft.graph.defaultManagedAppProtection entity.
get:
  tags:
    - deviceAppManagement.defaultManagedAppProtection
  summary: Get deploymentSummary from deviceAppManagement
  description: Navigation property to deployment summary of the configuration.
  operationId: deviceAppManagement.defaultManagedAppProtections.GetDeploymentSummary
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedAppPolicyDeploymentSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceAppManagement.defaultManagedAppProtection
  summary: Update the navigation property deploymentSummary in deviceAppManagement
  operationId: deviceAppManagement.defaultManagedAppProtections.UpdateDeploymentSummary
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.managedAppPolicyDeploymentSummary.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.managedAppPolicyDeploymentSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceAppManagement.defaultManagedAppProtection
  summary: Delete navigation property deploymentSummary for deviceAppManagement
  operationId: deviceAppManagement.defaultManagedAppProtections.DeleteDeploymentSummary
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: defaultManagedAppProtection-id
    in: path
    description: The unique identifier of defaultManagedAppProtection
    required: true
    schema:
      type: string
    x-ms-docs-key-type: defaultManagedAppProtection
