description: >-
  Provides operations to manage the deviceConfigurationDeviceStateSummaries
  property of the microsoft.graph.deviceManagement entity.
get:
  tags:
    - deviceManagement.deviceConfigurationDeviceStateSummary
  summary: Get deviceConfigurationDeviceStateSummary
  description: >-
    Read properties and relationships of the
    deviceConfigurationDeviceStateSummary object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-deviceconfigurationdevicestatesummary-get?view=graph-rest-1.0
  operationId: deviceManagement.GetDeviceConfigurationDeviceStateSummaries
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceConfigurationDeviceStateSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.deviceConfigurationDeviceStateSummary
  summary: Update deviceConfigurationDeviceStateSummary
  description: Update the properties of a deviceConfigurationDeviceStateSummary object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-deviceconfigurationdevicestatesummary-update?view=graph-rest-1.0
  operationId: deviceManagement.UpdateDeviceConfigurationDeviceStateSummaries
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.deviceConfigurationDeviceStateSummary.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceConfigurationDeviceStateSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.deviceConfigurationDeviceStateSummary
  summary: >-
    Delete navigation property deviceConfigurationDeviceStateSummaries for
    deviceManagement
  operationId: deviceManagement.DeleteDeviceConfigurationDeviceStateSummaries
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
