description: Provides operations to call the getOmaSettingPlainTextValue method.
get:
  tags:
    - deviceManagement.deviceConfiguration
  summary: Invoke function getOmaSettingPlainTextValue
  operationId: >-
    deviceManagement.deviceConfigurations.deviceConfiguration.getOmaSettingPlainTextValue
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              value:
                type: string
                nullable: true
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: function
parameters:
  - name: deviceConfiguration-id
    in: path
    description: The unique identifier of deviceConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceConfiguration
  - name: secretReferenceValueId
    in: path
    description: 'Usage: secretReferenceValueId=''{secretReferenceValueId}'''
    required: true
    schema:
      type: string
      nullable: true
