description: Provides operations to count the resources in the collection.
get:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Get the number of the resource
  operationId: deviceAppManagement.targetedManagedAppConfigurations.apps.GetCount-0ba7
  parameters:
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
  responses:
    2XX:
      $ref: ..\components\responses\ODataCountResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: targetedManagedAppConfiguration-id
    in: path
    description: The unique identifier of targetedManagedAppConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: targetedManagedAppConfiguration
