description: >-
  Provides operations to manage the metricValues property of the
  microsoft.graph.userExperienceAnalyticsCategory entity.
get:
  tags:
    - deviceManagement.userExperienceAnalyticsCategory
  summary: Get metricValues from deviceManagement
  description: The metric values for the user experience analytics category. Read-only.
  operationId: deviceManagement.userExperienceAnalyticsAppHealthOverview.ListMetricValues
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.userExperienceAnalyticsMetricCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - deviceManagement.userExperienceAnalyticsCategory
  summary: Create new navigation property to metricValues for deviceManagement
  operationId: deviceManagement.userExperienceAnalyticsAppHealthOverview.CreateMetricValues
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.userExperienceAnalyticsMetric.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.userExperienceAnalyticsMetric.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
x-ms-docs-grouped-path:
  - >-
    /deviceManagement/userExperienceAnalyticsCategories/{userExperienceAnalyticsCategory-id}/metricValues
