description: >-
  Provides operations to manage the deviceSettingStateSummaries property of the
  microsoft.graph.deviceCompliancePolicy entity.
get:
  tags:
    - deviceManagement.deviceCompliancePolicy
  summary: Get deviceSettingStateSummaries from deviceManagement
  description: Compliance Setting State Device Summary
  operationId: deviceManagement.deviceCompliancePolicies.ListDeviceSettingStateSummaries
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.settingStateDeviceSummaryCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - deviceManagement.deviceCompliancePolicy
  summary: >-
    Create new navigation property to deviceSettingStateSummaries for
    deviceManagement
  operationId: deviceManagement.deviceCompliancePolicies.CreateDeviceSettingStateSummaries
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.settingStateDeviceSummary.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.settingStateDeviceSummary.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: deviceCompliancePolicy-id
    in: path
    description: The unique identifier of deviceCompliancePolicy
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceCompliancePolicy
