description: >-
  Provides operations to manage the deviceComplianceSettingStates property of
  the microsoft.graph.deviceCompliancePolicySettingStateSummary entity.
get:
  tags:
    - deviceManagement.deviceCompliancePolicySettingStateSummary
  summary: Get deviceComplianceSettingState
  description: >-
    Read properties and relationships of the deviceComplianceSettingState
    object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecompliancesettingstate-get?view=graph-rest-1.0
  operationId: >-
    deviceManagement.deviceCompliancePolicySettingStateSummaries.GetDeviceComplianceSettingStates
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceComplianceSettingState.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - deviceManagement.deviceCompliancePolicySettingStateSummary
  summary: Update deviceComplianceSettingState
  description: Update the properties of a deviceComplianceSettingState object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecompliancesettingstate-update?view=graph-rest-1.0
  operationId: >-
    deviceManagement.deviceCompliancePolicySettingStateSummaries.UpdateDeviceComplianceSettingStates
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.deviceComplianceSettingState.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.deviceComplianceSettingState.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - deviceManagement.deviceCompliancePolicySettingStateSummary
  summary: Delete deviceComplianceSettingState
  description: Deletes a deviceComplianceSettingState.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/intune-deviceconfig-devicecompliancesettingstate-delete?view=graph-rest-1.0
  operationId: >-
    deviceManagement.deviceCompliancePolicySettingStateSummaries.DeleteDeviceComplianceSettingStates
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: deviceCompliancePolicySettingStateSummary-id
    in: path
    description: The unique identifier of deviceCompliancePolicySettingStateSummary
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceCompliancePolicySettingStateSummary
  - name: deviceComplianceSettingState-id
    in: path
    description: The unique identifier of deviceComplianceSettingState
    required: true
    schema:
      type: string
    x-ms-docs-key-type: deviceComplianceSettingState
