description: Provides operations to count the resources in the collection.
get:
  tags:
    - deviceAppManagement.targetedManagedAppConfiguration
  summary: Get the number of the resource
  operationId: deviceAppManagement.targetedManagedAppConfigurations.GetCount-8d50
  parameters:
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
  responses:
    2XX:
      $ref: ..\components\responses\ODataCountResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
