description: >-
  Provides operations to manage the federationConfigurations property of the
  microsoft.graph.directory entity.
get:
  tags:
    - directory.identityProviderBase
  summary: Get federationConfigurations from directory
  description: >-
    Configure domain federation with organizations whose identity provider (IdP)
    supports either the SAML or WS-Fed protocol.
  operationId: directory.GetFederationConfigurations
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.identityProviderBase.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - directory.identityProviderBase
  summary: Update the navigation property federationConfigurations in directory
  operationId: directory.UpdateFederationConfigurations
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.identityProviderBase.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.identityProviderBase.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - directory.identityProviderBase
  summary: Delete samlOrWsFedExternalDomainFederation
  description: Delete a samlOrWsFedExternalDomainFederation object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/samlorwsfedexternaldomainfederation-delete?view=graph-rest-1.0
  operationId: directory.DeleteFederationConfigurations
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: identityProviderBase-id
    in: path
    description: The unique identifier of identityProviderBase
    required: true
    schema:
      type: string
    x-ms-docs-key-type: identityProviderBase
