description: >-
  Provides operations to manage the allowedValues property of the
  microsoft.graph.customSecurityAttributeDefinition entity.
get:
  tags:
    - directory.customSecurityAttributeDefinition
  summary: List allowedValues
  description: Get a list of the allowedValue objects and their properties.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/customsecurityattributedefinition-list-allowedvalues?view=graph-rest-1.0
  operationId: directory.customSecurityAttributeDefinitions.ListAllowedValues
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.allowedValueCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - directory.customSecurityAttributeDefinition
  summary: Create allowedValue
  description: Create a new allowedValue object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/customsecurityattributedefinition-post-allowedvalues?view=graph-rest-1.0
  operationId: directory.customSecurityAttributeDefinitions.CreateAllowedValues
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.allowedValue.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.allowedValue.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: customSecurityAttributeDefinition-id
    in: path
    description: The unique identifier of customSecurityAttributeDefinition
    required: true
    schema:
      type: string
    x-ms-docs-key-type: customSecurityAttributeDefinition
