description: >-
  Provides operations to manage the federationConfigurations property of the
  microsoft.graph.directory entity.
get:
  tags:
    - directory.identityProviderBase
  summary: Get federationConfigurations from directory
  description: >-
    Configure domain federation with organizations whose identity provider (IdP)
    supports either the SAML or WS-Fed protocol.
  operationId: directory.ListFederationConfigurations
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.identityProviderBaseCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - directory.identityProviderBase
  summary: Create new navigation property to federationConfigurations for directory
  operationId: directory.CreateFederationConfigurations
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.identityProviderBase.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.identityProviderBase.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
