description: Casts the previous resource to application.
get:
  tags:
    - directory.directoryObject
  summary: >-
    Get the items of type microsoft.graph.application in the
    microsoft.graph.directoryObject collection
  operationId: directory.ListDeletedItems.AsApplication
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.applicationCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
