description: >-
  Provides operations to manage the federationConfiguration property of the
  microsoft.graph.domain entity.
get:
  tags:
    - domains.internalDomainFederation
  summary: Get internalDomainFederation
  description: Read the properties and relationships of an internalDomainFederation object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/internaldomainfederation-get?view=graph-rest-1.0
  operationId: domains.GetFederationConfiguration
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.internalDomainFederation.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - domains.internalDomainFederation
  summary: Update internalDomainFederation
  description: Update the properties of an internalDomainFederation object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/internaldomainfederation-update?view=graph-rest-1.0
  operationId: domains.UpdateFederationConfiguration
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.internalDomainFederation.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.internalDomainFederation.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - domains.internalDomainFederation
  summary: Delete internalDomainFederation
  description: Delete an internalDomainFederation object.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/internaldomainfederation-delete?view=graph-rest-1.0
  operationId: domains.DeleteFederationConfiguration
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: domain-id
    in: path
    description: The unique identifier of domain
    required: true
    schema:
      type: string
    x-ms-docs-key-type: domain
  - name: internalDomainFederation-id
    in: path
    description: The unique identifier of internalDomainFederation
    required: true
    schema:
      type: string
    x-ms-docs-key-type: internalDomainFederation
