description: >-
  Provides operations to manage the serviceConfigurationRecords property of the
  microsoft.graph.domain entity.
get:
  tags:
    - domains.domainDnsRecord
  summary: List serviceConfigurationRecords
  description: >-
    Retrieves a list of domainDnsRecord objects needed to enable services for
    the domain. Use the returned list to add records to the zone file of the
    domain. This can be done through the domain registrar or DNS server
    configuration.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/domain-list-serviceconfigurationrecords?view=graph-rest-1.0
  operationId: domains.ListServiceConfigurationRecords
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.domainDnsRecordCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - domains.domainDnsRecord
  summary: Create new navigation property to serviceConfigurationRecords for domains
  operationId: domains.CreateServiceConfigurationRecords
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.domainDnsRecord.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.domainDnsRecord.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: domain-id
    in: path
    description: The unique identifier of domain
    required: true
    schema:
      type: string
    x-ms-docs-key-type: domain
