description: Provides operations to call the usedRange method.
get:
  tags:
    - drives.driveItem
  summary: Invoke function usedRange
  operationId: >-
    drives.drive.items.driveItem.workbook.worksheets.workbookWorksheet.tables.workbookTable.columns.workbookTableColumn.headerRowRange.usedRange-63c8
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            anyOf:
              - $ref: ..\components\schemas\microsoft.graph.workbookRange.yaml
              - type: object
                nullable: true
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: function
parameters:
  - name: drive-id
    in: path
    description: The unique identifier of drive
    required: true
    schema:
      type: string
    x-ms-docs-key-type: drive
  - name: driveItem-id
    in: path
    description: The unique identifier of driveItem
    required: true
    schema:
      type: string
    x-ms-docs-key-type: driveItem
  - name: workbookWorksheet-id
    in: path
    description: The unique identifier of workbookWorksheet
    required: true
    schema:
      type: string
    x-ms-docs-key-type: workbookWorksheet
  - name: workbookTable-id
    in: path
    description: The unique identifier of workbookTable
    required: true
    schema:
      type: string
    x-ms-docs-key-type: workbookTable
  - name: workbookTableColumn-id
    in: path
    description: The unique identifier of workbookTableColumn
    required: true
    schema:
      type: string
    x-ms-docs-key-type: workbookTableColumn
  - name: valuesOnly
    in: path
    description: 'Usage: valuesOnly={valuesOnly}'
    required: true
    schema:
      type: boolean
      default: false
x-ms-docs-grouped-path:
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/names/{workbookNamedItem-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/names/{workbookNamedItem-id}/range()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/dataBodyRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/dataBodyRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/headerRowRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/headerRowRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/range()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/totalRowRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/totalRowRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/dataBodyRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/dataBodyRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/headerRowRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/headerRowRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/range()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/totalRowRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/totalRowRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/rows/{workbookTableRow-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/rows/{workbookTableRow-id}/range()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/cell(row={row},column={column})/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/cell(row={row},column={column})/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/range()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/range(address='{address}')/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/range(address='{address}')/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/names/{workbookNamedItem-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/names/{workbookNamedItem-id}/range()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/dataBodyRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/dataBodyRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/headerRowRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/range()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/totalRowRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/totalRowRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/dataBodyRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/dataBodyRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/headerRowRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/headerRowRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/range()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/totalRowRange()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/totalRowRange()/usedRange(valuesOnly={valuesOnly})
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/rows/{workbookTableRow-id}/range()/usedRange()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/rows/{workbookTableRow-id}/range()/usedRange(valuesOnly={valuesOnly})
