description: Provides operations to call the lastColumn method.
get:
  tags:
    - drives.driveItem
  summary: Invoke function lastColumn
  operationId: >-
    drives.drive.items.driveItem.workbook.worksheets.workbookWorksheet.usedRange.lastColumn-63c8
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            anyOf:
              - $ref: ..\components\schemas\microsoft.graph.workbookRange.yaml
              - type: object
                nullable: true
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: function
parameters:
  - name: drive-id
    in: path
    description: The unique identifier of drive
    required: true
    schema:
      type: string
    x-ms-docs-key-type: drive
  - name: driveItem-id
    in: path
    description: The unique identifier of driveItem
    required: true
    schema:
      type: string
    x-ms-docs-key-type: driveItem
  - name: workbookWorksheet-id
    in: path
    description: The unique identifier of workbookWorksheet
    required: true
    schema:
      type: string
    x-ms-docs-key-type: workbookWorksheet
  - name: valuesOnly
    in: path
    description: 'Usage: valuesOnly={valuesOnly}'
    required: true
    schema:
      type: boolean
      default: false
x-ms-docs-grouped-path:
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/names/{workbookNamedItem-id}/range()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/dataBodyRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/headerRowRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/range()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/totalRowRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/dataBodyRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/headerRowRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/range()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/totalRowRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/rows/{workbookTableRow-id}/range()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/cell(row={row},column={column})/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/range()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/range(address='{address}')/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/usedRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/names/{workbookNamedItem-id}/range()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/dataBodyRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/headerRowRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/range()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/columns/{workbookTableColumn-id}/totalRowRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/dataBodyRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/headerRowRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/range()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/totalRowRange()/lastColumn()
  - >-
    /drives/{drive-id}/items/{driveItem-id}/workbook/worksheets/{workbookWorksheet-id}/tables/{workbookTable-id}/rows/{workbookTableRow-id}/range()/lastColumn()
