description: >-
  Provides operations to manage the application property of the
  microsoft.graph.workbook entity.
get:
  tags:
    - drives.driveItem
  summary: Get application from drives
  operationId: drives.items.workbook.GetApplication
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.workbookApplication.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - drives.driveItem
  summary: Update the navigation property application in drives
  operationId: drives.items.workbook.UpdateApplication
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.workbookApplication.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.workbookApplication.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - drives.driveItem
  summary: Delete navigation property application for drives
  operationId: drives.items.workbook.DeleteApplication
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: drive-id
    in: path
    description: The unique identifier of drive
    required: true
    schema:
      type: string
    x-ms-docs-key-type: drive
  - name: driveItem-id
    in: path
    description: The unique identifier of driveItem
    required: true
    schema:
      type: string
    x-ms-docs-key-type: driveItem
