description: Provides operations to call the calculate method.
post:
  tags:
    - drives.driveItem
  summary: Invoke action calculate
  description: Recalculate all currently opened workbooks in Excel.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/workbookapplication-calculate?view=graph-rest-1.0
  operationId: drives.drive.items.driveItem.workbook.application.calculate
  requestBody:
    description: Action parameters
    content:
      application/json:
        schema:
          type: object
          properties:
            calculationType:
              type: string
    required: true
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: action
parameters:
  - name: drive-id
    in: path
    description: The unique identifier of drive
    required: true
    schema:
      type: string
    x-ms-docs-key-type: drive
  - name: driveItem-id
    in: path
    description: The unique identifier of driveItem
    required: true
    schema:
      type: string
    x-ms-docs-key-type: driveItem
