description: >-
  Provides operations to manage the gradingCategories property of the
  microsoft.graph.educationAssignmentSettings entity.
get:
  tags:
    - education.educationClass
  summary: Get gradingCategories from education
  description: >-
    When set, enables users to weight assignments differently when computing a
    class average grade.
  operationId: education.classes.assignmentSettings.GetGradingCategories
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.educationGradingCategory.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - education.educationClass
  summary: Update gradingCategory
  description: >-
    Update a single gradingCategory on the educationAssignmentSettings. Only
    teachers can perform this operation.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/educationgradingcategory-update?view=graph-rest-1.0
  operationId: education.classes.assignmentSettings.UpdateGradingCategories
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.educationGradingCategory.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.educationGradingCategory.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - education.educationClass
  summary: Delete navigation property gradingCategories for education
  operationId: education.classes.assignmentSettings.DeleteGradingCategories
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: educationClass-id
    in: path
    description: The unique identifier of educationClass
    required: true
    schema:
      type: string
    x-ms-docs-key-type: educationClass
  - name: educationGradingCategory-id
    in: path
    description: The unique identifier of educationGradingCategory
    required: true
    schema:
      type: string
    x-ms-docs-key-type: educationGradingCategory
