description: >-
  Provides operations to manage the gradingCategories property of the
  microsoft.graph.educationAssignmentSettings entity.
get:
  tags:
    - education.educationClass
  summary: Get gradingCategories from education
  description: >-
    When set, enables users to weight assignments differently when computing a
    class average grade.
  operationId: education.classes.assignmentSettings.ListGradingCategories
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.educationGradingCategoryCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - education.educationClass
  summary: Create new navigation property to gradingCategories for education
  operationId: education.classes.assignmentSettings.CreateGradingCategories
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.educationGradingCategory.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.educationGradingCategory.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: educationClass-id
    in: path
    description: The unique identifier of educationClass
    required: true
    schema:
      type: string
    x-ms-docs-key-type: educationClass
