description: >-
  Provides operations to manage the assignmentSettings property of the
  microsoft.graph.educationClass entity.
get:
  tags:
    - education.educationClass
  summary: Get assignmentSettings from education
  description: Specifies class-level assignments settings.
  operationId: education.classes.GetAssignmentSettings
  parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      description: Retrieved navigation property
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.educationAssignmentSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
patch:
  tags:
    - education.educationClass
  summary: Update educationAssignmentSettings
  description: >-
    Update the properties of an educationAssignmentSettings object. Only
    teachers can update these settings.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/educationassignmentsettings-update?view=graph-rest-1.0
  operationId: education.classes.UpdateAssignmentSettings
  requestBody:
    description: New navigation property values
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.educationAssignmentSettings.yaml
    required: true
  responses:
    2XX:
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.educationAssignmentSettings.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
delete:
  tags:
    - education.educationClass
  summary: Delete navigation property assignmentSettings for education
  operationId: education.classes.DeleteAssignmentSettings
  parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
  responses:
    '204':
      description: Success
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: educationClass-id
    in: path
    description: The unique identifier of educationClass
    required: true
    schema:
      type: string
    x-ms-docs-key-type: educationClass
