description: >-
  Provides operations to manage the settings property of the
  microsoft.graph.group entity.
get:
  tags:
    - groups.groupSetting
  summary: List settings
  description: Retrieve a list of tenant-level or group-specific group settings objects.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/group-list-settings?view=graph-rest-1.0
  operationId: groups.ListSettings
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.groupSettingCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - groups.groupSetting
  summary: Create settings
  description: >-
    Create a new setting based on the templates available in
    groupSettingTemplates. These settings can be at the tenant-level or at the
    group level. Group settings apply to only Microsoft 365 groups. The template
    named Group.Unified can be used to configure tenant-wide Microsoft 365 group
    settings, while the template named Group.Unified.Guest can be used to
    configure group-specific settings.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/group-post-settings?view=graph-rest-1.0
  operationId: groups.CreateSettings
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\microsoft.graph.groupSetting.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\microsoft.graph.groupSetting.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: group-id
    in: path
    description: The unique identifier of group
    required: true
    schema:
      type: string
    x-ms-docs-key-type: group
