description: >-
  Provides operations to manage the includeApplications property of the
  microsoft.graph.authenticationConditionsApplications entity.
get:
  tags:
    - identity.authenticationEventsFlow
  summary: List includeApplications (for a user flow)
  description: >-
    List the applications linked to an external identities self-service sign up
    user flow that's represented by an externalUsersSelfServiceSignupEventsFlow
    object. These are the applications for which the authentication experience
    that's defined by the user flow is enabled. To find the user flow that's
    linked to an application, see Example 4: List user flow associated with
    specific application ID.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/authenticationconditionsapplications-list-includeapplications?view=graph-rest-1.0
  operationId: identity.authenticationEventsFlows.ListIncludeApplications
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.authenticationConditionApplicationCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - identity.authenticationEventsFlow
  summary: Add includeApplication (to a user flow)
  description: >-
    Add or link an application to a user flow, or authenticationEventsFlow. This
    enables the authentication experience defined by the user flow to be enabled
    for the application. An application can only be linked to one user flow. The
    app must have an associated service principal in the tenant.
  externalDocs:
    description: Find more info here
    url: >-
      https://learn.microsoft.com/graph/api/authenticationconditionsapplications-post-includeapplications?view=graph-rest-1.0
  operationId: identity.authenticationEventsFlows.CreateIncludeApplications
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.authenticationConditionApplication.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.authenticationConditionApplication.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: authenticationEventsFlow-id
    in: path
    description: The unique identifier of authenticationEventsFlow
    required: true
    schema:
      type: string
    x-ms-docs-key-type: authenticationEventsFlow
x-ms-docs-grouped-path:
  - >-
    /identity/authenticationEventsFlows/{authenticationEventsFlow-id}/graph.externalUsersSelfServiceSignUpEventsFlow/conditions/applications/includeApplications
