description: Provides operations to count the resources in the collection.
get:
  tags:
    - identity.authenticationEventsFlow
  summary: Get the number of the resource
  operationId: >-
    identity.authenticationEventsFlows.AsExternalUsersSelfServiceSignUpEventsFlow.includeApplications.GetCount-c0bf
  parameters:
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
  responses:
    2XX:
      $ref: ..\components\responses\ODataCountResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
parameters:
  - name: authenticationEventsFlow-id
    in: path
    description: The unique identifier of authenticationEventsFlow
    required: true
    schema:
      type: string
    x-ms-docs-key-type: authenticationEventsFlow
