description: >-
  Provides operations to manage the includeApplications property of the
  microsoft.graph.authenticationConditionsApplications entity.
get:
  tags:
    - identity.authenticationEventsFlow
  summary: Get includeApplications from identity
  operationId: >-
    identity.authenticationEventsFlows.AsExternalUsersSelfServiceSignUpEventsFlow.ListIncludeApplications
  parameters:
    - $ref: ..\components\parameters\top.yaml
    - $ref: ..\components\parameters\skip.yaml
    - $ref: ..\components\parameters\search.yaml
    - $ref: ..\components\parameters\filter.yaml
    - $ref: ..\components\parameters\count.yaml
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
  responses:
    2XX:
      $ref: >-
        ..\components\responses\microsoft.graph.authenticationConditionApplicationCollectionResponse.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-pageable:
    nextLinkName: '@odata.nextLink'
    operationName: listMore
  x-ms-docs-operation-type: operation
post:
  tags:
    - identity.authenticationEventsFlow
  summary: Create new navigation property to includeApplications for identity
  operationId: >-
    identity.authenticationEventsFlows.AsExternalUsersSelfServiceSignUpEventsFlow.CreateIncludeApplications
  requestBody:
    description: New navigation property
    content:
      application/json:
        schema:
          $ref: >-
            ..\components\schemas\microsoft.graph.authenticationConditionApplication.yaml
    required: true
  responses:
    2XX:
      description: Created navigation property.
      content:
        application/json:
          schema:
            $ref: >-
              ..\components\schemas\microsoft.graph.authenticationConditionApplication.yaml
    4XX:
      $ref: ..\components\responses\error.yaml
    5XX:
      $ref: ..\components\responses\error.yaml
  x-ms-docs-operation-type: operation
parameters:
  - name: authenticationEventsFlow-id
    in: path
    description: The unique identifier of authenticationEventsFlow
    required: true
    schema:
      type: string
    x-ms-docs-key-type: authenticationEventsFlow
x-ms-docs-grouped-path:
  - >-
    /identity/authenticationEventsFlows/{authenticationEventsFlow-id}/conditions/applications/includeApplications
