allOf:
  - $ref: .\microsoft.graph.appleDeviceFeaturesConfigurationBase.yaml
  - title: iosDeviceFeaturesConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      assetTagTemplate:
        type: string
        description: >-
          Asset tag information for the device, displayed on the login window
          and lock screen.
        nullable: true
      homeScreenDockIcons:
        type: array
        items:
          $ref: .\microsoft.graph.iosHomeScreenItem.yaml
        description: >-
          A list of app and folders to appear on the Home Screen Dock. This
          collection can contain a maximum of 500 elements.
      homeScreenPages:
        type: array
        items:
          $ref: .\microsoft.graph.iosHomeScreenPage.yaml
        description: >-
          A list of pages on the Home Screen. This collection can contain a
          maximum of 500 elements.
      lockScreenFootnote:
        type: string
        description: >-
          A footnote displayed on the login window and lock screen. Available in
          iOS 9.3.1 and later.
        nullable: true
      notificationSettings:
        type: array
        items:
          $ref: .\microsoft.graph.iosNotificationSettings.yaml
        description: >-
          Notification settings for each bundle id. Applicable to devices in
          supervised mode only (iOS 9.3 and later). This collection can contain
          a maximum of 500 elements.
      '@odata.type':
        type: string
        default: '#microsoft.graph.iosDeviceFeaturesConfiguration'
    description: iOS Device Features Configuration Profile.
x-ms-discriminator-value: '#microsoft.graph.iosDeviceFeaturesConfiguration'
