title: Collection of microsoft.graph.preAuthorizedApplication
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.preAuthorizedApplication.yaml
