allOf:
  - $ref: .\microsoft.graph.deviceConfiguration.yaml
  - title: windows10TeamGeneralConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      azureOperationalInsightsBlockTelemetry:
        type: boolean
        description: Indicates whether or not to Block Azure Operational Insights.
      azureOperationalInsightsWorkspaceId:
        type: string
        description: The Azure Operational Insights workspace id.
        nullable: true
      azureOperationalInsightsWorkspaceKey:
        type: string
        description: The Azure Operational Insights Workspace key.
        nullable: true
      connectAppBlockAutoLaunch:
        type: boolean
        description: >-
          Specifies whether to automatically launch the Connect app whenever a
          projection is initiated.
      maintenanceWindowBlocked:
        type: boolean
        description: >-
          Indicates whether or not to Block setting a maintenance window for
          device updates.
      maintenanceWindowDurationInHours:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Maintenance window duration for device updates. Valid values 0 to 5
        format: int32
        nullable: true
      maintenanceWindowStartTime:
        pattern: ^([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?$
        type: string
        description: Maintenance window start time for device updates.
        format: time
        nullable: true
      miracastBlocked:
        type: boolean
        description: Indicates whether or not to Block wireless projection.
      miracastChannel:
        $ref: .\microsoft.graph.miracastChannel.yaml
      miracastRequirePin:
        type: boolean
        description: Indicates whether or not to require a pin for wireless projection.
      settingsBlockMyMeetingsAndFiles:
        type: boolean
        description: >-
          Specifies whether to disable the 'My meetings and files' feature in
          the Start menu, which shows the signed-in user's meetings and files
          from Office 365.
      settingsBlockSessionResume:
        type: boolean
        description: >-
          Specifies whether to allow the ability to resume a session when the
          session times out.
      settingsBlockSigninSuggestions:
        type: boolean
        description: >-
          Specifies whether to disable auto-populating of the sign-in dialog
          with invitees from scheduled meetings.
      settingsDefaultVolume:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: >-
          Specifies the default volume value for a new session. Permitted values
          are 0-100. The default is 45. Valid values 0 to 100
        format: int32
        nullable: true
      settingsScreenTimeoutInMinutes:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Specifies the number of minutes until the Hub screen turns off.
        format: int32
        nullable: true
      settingsSessionTimeoutInMinutes:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Specifies the number of minutes until the session times out.
        format: int32
        nullable: true
      settingsSleepTimeoutInMinutes:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Specifies the number of minutes until the Hub enters sleep mode.
        format: int32
        nullable: true
      welcomeScreenBackgroundImageUrl:
        type: string
        description: >-
          The welcome screen background image URL. The URL must use the HTTPS
          protocol and return a PNG image.
        nullable: true
      welcomeScreenBlockAutomaticWakeUp:
        type: boolean
        description: >-
          Indicates whether or not to Block the welcome screen from waking up
          automatically when someone enters the room.
      welcomeScreenMeetingInformation:
        $ref: .\microsoft.graph.welcomeScreenMeetingInformation.yaml
      '@odata.type':
        type: string
        default: '#microsoft.graph.windows10TeamGeneralConfiguration'
    description: >-
      This topic provides descriptions of the declared methods, properties and
      relationships exposed by the windows10TeamGeneralConfiguration resource.
x-ms-discriminator-value: '#microsoft.graph.windows10TeamGeneralConfiguration'
