title: virtualEventSettings
required:
  - '@odata.type'
type: object
properties:
  isAttendeeEmailNotificationEnabled:
    type: boolean
    description: Indicates whether virtual event attendees receive email notifications.
    nullable: true
  '@odata.type':
    type: string
