title: Collection of settingStateDeviceSummary
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.settingStateDeviceSummary.yaml
