allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: enrollmentConfigurationAssignment
    required:
      - '@odata.type'
    type: object
    properties:
      target:
        anyOf:
          - $ref: .\microsoft.graph.deviceAndAppManagementAssignmentTarget.yaml
          - type: object
            nullable: true
        description: Represents an assignment to managed devices in the tenant
      '@odata.type':
        type: string
    description: Enrollment Configuration Assignment
x-ms-discriminator-value: '#microsoft.graph.enrollmentConfigurationAssignment'
