title: Collection of windows81GeneralConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.windows81GeneralConfiguration.yaml
