allOf:
  - $ref: .\microsoft.graph.authenticationCombinationConfiguration.yaml
  - title: fido2CombinationConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      allowedAAGUIDs:
        type: array
        items:
          type: string
        description: >-
          A list of AAGUIDs allowed to be used as part of the specified
          authentication method combinations.
      '@odata.type':
        type: string
        default: '#microsoft.graph.fido2CombinationConfiguration'
x-ms-discriminator-value: '#microsoft.graph.fido2CombinationConfiguration'
