title: parentalControlSettings
required:
  - '@odata.type'
type: object
properties:
  countriesBlockedForMinors:
    type: array
    items:
      type: string
      nullable: true
    description: >-
      Specifies the two-letter ISO country codes. Access to the application will
      be blocked for minors from the countries specified in this list.
  legalAgeGroupRule:
    type: string
    description: >-
      Specifies the legal age group rule that applies to users of the app. Can
      be set to one of the following values: ValueDescriptionAllowDefault.
      Enforces the legal minimum. This means parental consent is required for
      minors in the European Union and
      Korea.RequireConsentForPrivacyServicesEnforces the user to specify date of
      birth to comply with COPPA rules. RequireConsentForMinorsRequires parental
      consent for ages below 18, regardless of country minor
      rules.RequireConsentForKidsRequires parental consent for ages below 14,
      regardless of country minor rules.BlockMinorsBlocks minors from using the
      app.
    nullable: true
  '@odata.type':
    type: string
