title: implicitGrantSettings
required:
  - '@odata.type'
type: object
properties:
  enableAccessTokenIssuance:
    type: boolean
    description: >-
      Specifies whether this web application can request an access token using
      the OAuth 2.0 implicit flow.
    nullable: true
  enableIdTokenIssuance:
    type: boolean
    description: >-
      Specifies whether this web application can request an ID token using the
      OAuth 2.0 implicit flow.
    nullable: true
  '@odata.type':
    type: string
