allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: certificateBasedAuthConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      certificateAuthorities:
        type: array
        items:
          $ref: .\microsoft.graph.certificateAuthority.yaml
        description: >-
          Collection of certificate authorities which creates a trusted
          certificate chain.
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.certificateBasedAuthConfiguration'
