allOf:
  - $ref: .\microsoft.graph.authenticationMethodConfiguration.yaml
  - title: emailAuthenticationMethodConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      allowExternalIdToUseEmailOtp:
        anyOf:
          - $ref: .\microsoft.graph.externalEmailOtpState.yaml
          - type: object
            nullable: true
        description: >-
          Determines whether email OTP is usable by external users for
          authentication. Possible values are: default, enabled, disabled,
          unknownFutureValue. Tenants in the default state who didn't use public
          preview have email OTP enabled beginning in October 2021.
      includeTargets:
        type: array
        items:
          $ref: .\microsoft.graph.authenticationMethodTarget.yaml
        description: >-
          A collection of groups that are enabled to use the authentication
          method.
        x-ms-navigationProperty: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.emailAuthenticationMethodConfiguration'
x-ms-discriminator-value: '#microsoft.graph.emailAuthenticationMethodConfiguration'
