title: Collection of macOSDeviceFeaturesConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.macOSDeviceFeaturesConfiguration.yaml
