title: publicClientApplication
required:
  - '@odata.type'
type: object
properties:
  redirectUris:
    type: array
    items:
      type: string
    description: >-
      Specifies the URLs where user tokens are sent for sign-in, or the redirect
      URIs where OAuth 2.0 authorization codes and access tokens are sent. For
      iOS and macOS apps, specify the value following the syntax
      msauth.{BUNDLEID}://auth, replacing '{BUNDLEID}'. For example, if the
      bundle ID is com.microsoft.identitysample.MSALiOS, the URI is
      msauth.com.microsoft.identitysample.MSALiOS://auth.
  '@odata.type':
    type: string
