allOf:
  - $ref: .\microsoft.graph.security.alertEvidence.yaml
  - title: mailboxConfigurationEvidence
    required:
      - '@odata.type'
    type: object
    properties:
      configurationId:
        type: string
        nullable: true
      configurationType:
        anyOf:
          - $ref: .\microsoft.graph.security.mailboxConfigurationType.yaml
          - type: object
            nullable: true
      displayName:
        type: string
        nullable: true
      externalDirectoryObjectId:
        pattern: >-
          ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
        type: string
        format: uuid
        nullable: true
      mailboxPrimaryAddress:
        type: string
        nullable: true
      upn:
        type: string
        nullable: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.security.mailboxConfigurationEvidence'
x-ms-discriminator-value: '#microsoft.graph.security.mailboxConfigurationEvidence'
