allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: managedAppPolicyDeploymentSummary
    required:
      - '@odata.type'
    type: object
    properties:
      configurationDeployedUserCount:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Not yet documented
        format: int32
      configurationDeploymentSummaryPerApp:
        type: array
        items:
          $ref: .\microsoft.graph.managedAppPolicyDeploymentSummaryPerApp.yaml
        description: Not yet documented
      displayName:
        type: string
        description: Not yet documented
        nullable: true
      lastRefreshTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: Not yet documented
        format: date-time
      version:
        type: string
        description: Version of the entity.
        nullable: true
      '@odata.type':
        type: string
    description: >-
      The ManagedAppEntity is the base entity type for all other entity types
      under app management workflow.
x-ms-discriminator-value: '#microsoft.graph.managedAppPolicyDeploymentSummary'
