allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: deviceConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      createdDateTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: DateTime the object was created.
        format: date-time
      description:
        type: string
        description: Admin provided description of the Device Configuration.
        nullable: true
      displayName:
        type: string
        description: Admin provided name of the device configuration.
      lastModifiedDateTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: DateTime the object was last modified.
        format: date-time
      version:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Version of the device configuration.
        format: int32
      assignments:
        type: array
        items:
          $ref: .\microsoft.graph.deviceConfigurationAssignment.yaml
        description: The list of assignments for the device configuration profile.
        x-ms-navigationProperty: true
      deviceSettingStateSummaries:
        type: array
        items:
          $ref: .\microsoft.graph.settingStateDeviceSummary.yaml
        description: Device Configuration Setting State Device Summary
        x-ms-navigationProperty: true
      deviceStatuses:
        type: array
        items:
          $ref: .\microsoft.graph.deviceConfigurationDeviceStatus.yaml
        description: Device configuration installation status by device.
        x-ms-navigationProperty: true
      deviceStatusOverview:
        anyOf:
          - $ref: .\microsoft.graph.deviceConfigurationDeviceOverview.yaml
          - type: object
            nullable: true
        description: Device Configuration devices status overview
        x-ms-navigationProperty: true
      userStatuses:
        type: array
        items:
          $ref: .\microsoft.graph.deviceConfigurationUserStatus.yaml
        description: Device configuration installation status by user.
        x-ms-navigationProperty: true
      userStatusOverview:
        anyOf:
          - $ref: .\microsoft.graph.deviceConfigurationUserOverview.yaml
          - type: object
            nullable: true
        description: Device Configuration users status overview
        x-ms-navigationProperty: true
      '@odata.type':
        type: string
    description: Device Configuration.
    discriminator:
      propertyName: '@odata.type'
      mapping:
        '#microsoft.graph.androidCustomConfiguration': .\microsoft.graph.androidCustomConfiguration.yaml
        '#microsoft.graph.androidGeneralDeviceConfiguration': .\microsoft.graph.androidGeneralDeviceConfiguration.yaml
        '#microsoft.graph.androidWorkProfileCustomConfiguration': .\microsoft.graph.androidWorkProfileCustomConfiguration.yaml
        '#microsoft.graph.androidWorkProfileGeneralDeviceConfiguration': .\microsoft.graph.androidWorkProfileGeneralDeviceConfiguration.yaml
        '#microsoft.graph.appleDeviceFeaturesConfigurationBase': .\microsoft.graph.appleDeviceFeaturesConfigurationBase.yaml
        '#microsoft.graph.iosDeviceFeaturesConfiguration': .\microsoft.graph.iosDeviceFeaturesConfiguration.yaml
        '#microsoft.graph.macOSDeviceFeaturesConfiguration': .\microsoft.graph.macOSDeviceFeaturesConfiguration.yaml
        '#microsoft.graph.editionUpgradeConfiguration': .\microsoft.graph.editionUpgradeConfiguration.yaml
        '#microsoft.graph.iosCertificateProfile': .\microsoft.graph.iosCertificateProfile.yaml
        '#microsoft.graph.iosCustomConfiguration': .\microsoft.graph.iosCustomConfiguration.yaml
        '#microsoft.graph.iosGeneralDeviceConfiguration': .\microsoft.graph.iosGeneralDeviceConfiguration.yaml
        '#microsoft.graph.iosUpdateConfiguration': .\microsoft.graph.iosUpdateConfiguration.yaml
        '#microsoft.graph.macOSCustomConfiguration': .\microsoft.graph.macOSCustomConfiguration.yaml
        '#microsoft.graph.macOSGeneralDeviceConfiguration': .\microsoft.graph.macOSGeneralDeviceConfiguration.yaml
        '#microsoft.graph.sharedPCConfiguration': .\microsoft.graph.sharedPCConfiguration.yaml
        '#microsoft.graph.windows10CustomConfiguration': .\microsoft.graph.windows10CustomConfiguration.yaml
        '#microsoft.graph.windows10EndpointProtectionConfiguration': .\microsoft.graph.windows10EndpointProtectionConfiguration.yaml
        '#microsoft.graph.windows10EnterpriseModernAppManagementConfiguration': >-
          .\microsoft.graph.windows10EnterpriseModernAppManagementConfiguration.yaml
        '#microsoft.graph.windows10GeneralConfiguration': .\microsoft.graph.windows10GeneralConfiguration.yaml
        '#microsoft.graph.windows10SecureAssessmentConfiguration': .\microsoft.graph.windows10SecureAssessmentConfiguration.yaml
        '#microsoft.graph.windows10TeamGeneralConfiguration': .\microsoft.graph.windows10TeamGeneralConfiguration.yaml
        '#microsoft.graph.windows81GeneralConfiguration': .\microsoft.graph.windows81GeneralConfiguration.yaml
        '#microsoft.graph.windowsDefenderAdvancedThreatProtectionConfiguration': >-
          .\microsoft.graph.windowsDefenderAdvancedThreatProtectionConfiguration.yaml
        '#microsoft.graph.windowsPhone81CustomConfiguration': .\microsoft.graph.windowsPhone81CustomConfiguration.yaml
        '#microsoft.graph.windowsPhone81GeneralConfiguration': .\microsoft.graph.windowsPhone81GeneralConfiguration.yaml
        '#microsoft.graph.windowsUpdateForBusinessConfiguration': .\microsoft.graph.windowsUpdateForBusinessConfiguration.yaml
