allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: deviceEnrollmentConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      createdDateTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: Created date time in UTC of the device enrollment configuration
        format: date-time
      description:
        type: string
        description: The description of the device enrollment configuration
        nullable: true
      displayName:
        type: string
        description: The display name of the device enrollment configuration
        nullable: true
      lastModifiedDateTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: Last modified date time in UTC of the device enrollment configuration
        format: date-time
      priority:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: >-
          Priority is used when a user exists in multiple groups that are
          assigned enrollment configuration. Users are subject only to the
          configuration with the lowest priority value.
        format: int32
      version:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: The version of the device enrollment configuration
        format: int32
      assignments:
        type: array
        items:
          $ref: .\microsoft.graph.enrollmentConfigurationAssignment.yaml
        description: The list of group assignments for the device configuration profile
        x-ms-navigationProperty: true
      '@odata.type':
        type: string
    description: The Base Class of Device Enrollment Configuration
    discriminator:
      propertyName: '@odata.type'
      mapping:
        '#microsoft.graph.deviceEnrollmentLimitConfiguration': .\microsoft.graph.deviceEnrollmentLimitConfiguration.yaml
        '#microsoft.graph.deviceEnrollmentPlatformRestrictionsConfiguration': >-
          .\microsoft.graph.deviceEnrollmentPlatformRestrictionsConfiguration.yaml
        '#microsoft.graph.deviceEnrollmentWindowsHelloForBusinessConfiguration': >-
          .\microsoft.graph.deviceEnrollmentWindowsHelloForBusinessConfiguration.yaml
        '#microsoft.graph.windows10EnrollmentCompletionPageConfiguration': .\microsoft.graph.windows10EnrollmentCompletionPageConfiguration.yaml
