allOf:
  - $ref: .\microsoft.graph.deviceConfiguration.yaml
  - title: editionUpgradeConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      license:
        type: string
        description: Edition Upgrade License File Content.
        nullable: true
      licenseType:
        $ref: .\microsoft.graph.editionUpgradeLicenseType.yaml
      productKey:
        type: string
        description: Edition Upgrade Product Key.
        nullable: true
      targetEdition:
        $ref: .\microsoft.graph.windows10EditionType.yaml
      '@odata.type':
        type: string
        default: '#microsoft.graph.editionUpgradeConfiguration'
    description: Windows 10 Edition Upgrade configuration.
x-ms-discriminator-value: '#microsoft.graph.editionUpgradeConfiguration'
