title: Collection of windowsPhone81CustomConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.windowsPhone81CustomConfiguration.yaml
