allOf:
  - $ref: .\microsoft.graph.managedAppConfiguration.yaml
  - title: targetedManagedAppConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      deployedAppCount:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Count of apps to which the current policy is deployed.
        format: int32
      isAssigned:
        type: boolean
        description: Indicates if the policy is deployed to any inclusion groups or not.
      apps:
        type: array
        items:
          $ref: .\microsoft.graph.managedMobileApp.yaml
        description: List of apps to which the policy is deployed.
        x-ms-navigationProperty: true
      assignments:
        type: array
        items:
          $ref: .\microsoft.graph.targetedManagedAppPolicyAssignment.yaml
        description: >-
          Navigation property to list of inclusion and exclusion groups to which
          the policy is deployed.
        x-ms-navigationProperty: true
      deploymentSummary:
        anyOf:
          - $ref: .\microsoft.graph.managedAppPolicyDeploymentSummary.yaml
          - type: object
            nullable: true
        description: Navigation property to deployment summary of the configuration.
        x-ms-navigationProperty: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.targetedManagedAppConfiguration'
    description: >-
      Configuration used to deliver a set of custom settings as-is to all users
      in the targeted security group
x-ms-discriminator-value: '#microsoft.graph.targetedManagedAppConfiguration'
