title: mobileAppInstallTimeSettings
required:
  - '@odata.type'
type: object
properties:
  deadlineDateTime:
    pattern: >-
      ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
    type: string
    description: The time at which the app should be installed.
    format: date-time
    nullable: true
  startDateTime:
    pattern: >-
      ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
    type: string
    description: The time at which the app should be available for installation.
    format: date-time
    nullable: true
  useLocalTime:
    type: boolean
    description: >-
      Whether the local device time or UTC time should be used when determining
      the available and deadline times.
  '@odata.type':
    type: string
description: >-
  Contains properties used to determine when to offer an app to devices and when
  to install the app on devices.
