allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: lifecycleManagementSettings
    required:
      - '@odata.type'
    type: object
    properties:
      emailSettings:
        $ref: .\microsoft.graph.emailSettings.yaml
      workflowScheduleIntervalInHours:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: >-
          The interval in hours at which all workflows running in the tenant
          should be scheduled for execution. This interval has a minimum value
          of 1 and a maximum value of 24. The default value is 3 hours.
        format: int32
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.identityGovernance.lifecycleManagementSettings'
