title: Collection of androidWorkProfileCustomConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.androidWorkProfileCustomConfiguration.yaml
