title: accessReviewScheduleSettings
required:
  - '@odata.type'
type: object
properties:
  applyActions:
    type: array
    items:
      $ref: .\microsoft.graph.accessReviewApplyAction.yaml
    description: >-
      Optional field. Describes the  actions to take once a review is complete.
      There are two types that are currently supported: removeAccessApplyAction
      (default) and disableAndDeleteUserApplyAction. Field only needs to be
      specified in the case of disableAndDeleteUserApplyAction.
  autoApplyDecisionsEnabled:
    type: boolean
    description: >-
      Indicates whether decisions are automatically applied. When set to false,
      an admin must apply the decisions manually once the reviewer completes the
      access review. When set to true, decisions are applied automatically after
      the access review instance duration ends, whether or not the reviewers
      have responded. Default value is false.  CAUTION: If both
      autoApplyDecisionsEnabled and defaultDecisionEnabled are true, all access
      for the principals to the resource risks being revoked if the reviewers
      fail to respond.
  decisionHistoriesForReviewersEnabled:
    type: boolean
    description: >-
      Indicates whether decisions on previous access review stages are available
      for reviewers on an accessReviewInstance with multiple subsequent stages.
      If not provided, the default is disabled (false).
    nullable: true
  defaultDecision:
    type: string
    description: >-
      Decision chosen if defaultDecisionEnabled is enabled. Can be one of
      Approve, Deny, or Recommendation.
    nullable: true
  defaultDecisionEnabled:
    type: boolean
    description: >-
      Indicates whether the default decision is enabled or disabled when
      reviewers do not respond. Default value is false.  CAUTION: If both
      autoApplyDecisionsEnabled and defaultDecisionEnabled are true, all access
      for the principals to the resource risks being revoked if the reviewers
      fail to respond.
  instanceDurationInDays:
    maximum: 2147483647
    minimum: -2147483648
    type: number
    description: >-
      Duration of an access review instance in days. NOTE: If the stageSettings
      of the accessReviewScheduleDefinition object is defined, its
      durationInDays setting will be used instead of the value of this property.
    format: int32
  justificationRequiredOnApproval:
    type: boolean
    description: >-
      Indicates whether reviewers are required to provide justification with
      their decision. Default value is false.
  mailNotificationsEnabled:
    type: boolean
    description: Indicates whether emails are enabled or disabled. Default value is false.
  recommendationInsightSettings:
    type: array
    items:
      $ref: .\microsoft.graph.accessReviewRecommendationInsightSetting.yaml
    description: >-
      Optional. Describes the types of insights that aid reviewers to make
      access review decisions. NOTE: If the stageSettings of the
      accessReviewScheduleDefinition object is defined, its
      recommendationInsightSettings setting will be used instead of the value of
      this property.
  recommendationLookBackDuration:
    pattern: ^-?P([0-9]+D)?(T([0-9]+H)?([0-9]+M)?([0-9]+([.][0-9]+)?S)?)?$
    type: string
    description: >-
      Optional field. Indicates the period of inactivity (with respect to the
      start date of the review instance) that recommendations will be configured
      from. The recommendation will be to deny if the user is inactive during
      the look-back duration. For reviews of groups and Microsoft Entra roles,
      any duration is accepted. For reviews of applications, 30 days is the
      maximum duration. If not specified, the duration is 30 days. NOTE: If the
      stageSettings of the accessReviewScheduleDefinition object is defined, its
      recommendationLookBackDuration setting will be used instead of the value
      of this property.
    format: duration
    nullable: true
  recommendationsEnabled:
    type: boolean
    description: >-
      Indicates whether decision recommendations are enabled or disabled. NOTE:
      If the stageSettings of the accessReviewScheduleDefinition object is
      defined, its recommendationsEnabled setting will be used instead of the
      value of this property.
  recurrence:
    anyOf:
      - $ref: .\microsoft.graph.patternedRecurrence.yaml
      - type: object
        nullable: true
    description: >-
      Detailed settings for recurrence using the standard Outlook recurrence
      object. Note: Only dayOfMonth, interval, and type (weekly,
      absoluteMonthly) properties are supported. Use the property startDate on
      recurrenceRange to determine the day the review starts.
  reminderNotificationsEnabled:
    type: boolean
    description: >-
      Indicates whether reminders are enabled or disabled. Default value is
      false.
  '@odata.type':
    type: string
