allOf:
  - $ref: .\microsoft.graph.invitationRedemptionIdentityProviderConfiguration.yaml
  - title: defaultInvitationRedemptionIdentityProviderConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.defaultInvitationRedemptionIdentityProviderConfiguration'
