title: Collection of microsoft.graph.deviceCompliancePolicySettingState
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.deviceCompliancePolicySettingState.yaml
