allOf:
  - $ref: .\microsoft.graph.conditionalAccessSessionControl.yaml
  - title: applicationEnforcedRestrictionsSessionControl
    required:
      - '@odata.type'
    type: object
    properties:
      '@odata.type':
        type: string
        default: '#microsoft.graph.applicationEnforcedRestrictionsSessionControl'
x-ms-discriminator-value: '#microsoft.graph.applicationEnforcedRestrictionsSessionControl'
