allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: accessPackageResourceEnvironment
    required:
      - '@odata.type'
    type: object
    properties:
      connectionInfo:
        anyOf:
          - $ref: .\microsoft.graph.connectionInfo.yaml
          - type: object
            nullable: true
        description: >-
          Connection information of an environment used to connect to a
          resource.
      createdDateTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: >-
          The date and time that this object was created. The DateTimeOffset
          type represents date and time information using ISO 8601 format and is
          always in UTC time. For example, midnight UTC on Jan 1, 2014 is
          2014-01-01T00:00:00Z.
        format: date-time
        nullable: true
      description:
        type: string
        description: The description of this object.
        nullable: true
      displayName:
        type: string
        description: The display name of this object.
        nullable: true
      isDefaultEnvironment:
        type: boolean
        description: >-
          Determines whether this is default environment or not. It is set to
          true for all static origin systems, such as Microsoft Entra groups and
          Microsoft Entra Applications.
        nullable: true
      modifiedDateTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: >-
          The date and time that this object was last modified. The
          DateTimeOffset type represents date and time information using ISO
          8601 format and is always in UTC time. For example, midnight UTC on
          Jan 1, 2014 is 2014-01-01T00:00:00Z.
        format: date-time
        nullable: true
      originId:
        type: string
        description: The unique identifier of this environment in the origin system.
        nullable: true
      originSystem:
        type: string
        description: >-
          The type of the resource in the origin system, that is,
          SharePointOnline. Requires $filter (eq).
        nullable: true
      resources:
        type: array
        items:
          $ref: .\microsoft.graph.accessPackageResource.yaml
        description: Read-only. Required.
        x-ms-navigationProperty: true
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.accessPackageResourceEnvironment'
