allOf:
  - $ref: .\microsoft.graph.deviceConfiguration.yaml
  - title: windows10SecureAssessmentConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      allowPrinting:
        type: boolean
        description: >-
          Indicates whether or not to allow the app from printing during the
          test.
      allowScreenCapture:
        type: boolean
        description: >-
          Indicates whether or not to allow screen capture capability during a
          test.
      allowTextSuggestion:
        type: boolean
        description: Indicates whether or not to allow text suggestions during the test.
      configurationAccount:
        type: string
        description: >-
          The account used to configure the Windows device for taking the test.
          The user can be a domain account (domain/user), an AAD account
          (username@tenant.com) or a local account (username).
        nullable: true
      launchUri:
        type: string
        description: >-
          Url link to an assessment that's automatically loaded when the secure
          assessment browser is launched. It has to be a valid Url
          (http[s]://msdn.microsoft.com/).
        nullable: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.windows10SecureAssessmentConfiguration'
    description: >-
      This topic provides descriptions of the declared methods, properties and
      relationships exposed by the secureAssessment resource.
x-ms-discriminator-value: '#microsoft.graph.windows10SecureAssessmentConfiguration'
