allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: insightsSettings
    required:
      - '@odata.type'
    type: object
    properties:
      disabledForGroup:
        type: string
        description: >-
          The ID of a Microsoft Entra group, of which the specified type of
          insights are disabled for its members. The default value is null.
          Optional.
        nullable: true
      isEnabledInOrganization:
        type: boolean
        description: >-
          true if insights of the specified type are enabled for the
          organization; false if insights of the specified type are disabled for
          all users without exceptions. The default value is true. Optional.
        nullable: true
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.insightsSettings'
