allOf:
  - $ref: .\microsoft.graph.mobileAppAssignmentSettings.yaml
  - title: iosLobAppAssignmentSettings
    required:
      - '@odata.type'
    type: object
    properties:
      isRemovable:
        type: boolean
        description: >-
          When TRUE, indicates that the app can be uninstalled by the user. When
          FALSE, indicates that the app cannot be uninstalled by the user. By
          default, this property is set to null which internally is treated as
          TRUE.
        nullable: true
      uninstallOnDeviceRemoval:
        type: boolean
        description: >-
          When TRUE, indicates that the app should be uninstalled when the
          device is removed from Intune. When FALSE, indicates that the app will
          not be uninstalled when the device is removed from Intune. By default,
          property is set to null which internally is treated as TRUE.
        nullable: true
      vpnConfigurationId:
        type: string
        description: >-
          This is the unique identifier (Id) of the VPN Configuration to apply
          to the app.
        nullable: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.iosLobAppAssignmentSettings'
    description: Contains properties used to assign an iOS LOB mobile app to a group.
x-ms-discriminator-value: '#microsoft.graph.iosLobAppAssignmentSettings'
