allOf:
  - $ref: .\microsoft.graph.appManagementConfiguration.yaml
  - title: customAppManagementConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      '@odata.type':
        type: string
        default: '#microsoft.graph.customAppManagementConfiguration'
x-ms-discriminator-value: '#microsoft.graph.customAppManagementConfiguration'
