allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: teamsAppSettings
    required:
      - '@odata.type'
    type: object
    properties:
      allowUserRequestsForAppAccess:
        type: boolean
        description: >-
          Indicates whether users are allowed to request access to the
          unavailable Teams apps.
        nullable: true
      isUserPersonalScopeResourceSpecificConsentEnabled:
        type: boolean
        description: >-
          Indicates whether resource-specific consent for personal scope in
          Teams apps is enabled for the tenant. True indicates that Teams apps
          that are allowed in the tenant and require resource-specific
          permissions can be installed in the personal scope. False blocks the
          installation of any Teams app that requires resource-specific
          permissions in the personal scope.
        nullable: true
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.teamsAppSettings'
