title: lobbyBypassSettings
required:
  - '@odata.type'
type: object
properties:
  isDialInBypassEnabled:
    type: boolean
    description: >-
      Specifies whether or not to always let dial-in callers bypass the lobby.
      Optional.
    nullable: true
  scope:
    anyOf:
      - $ref: .\microsoft.graph.lobbyBypassScope.yaml
      - type: object
        nullable: true
    description: >-
      Specifies the type of participants that are automatically admitted into a
      meeting, bypassing the lobby. Optional.
  '@odata.type':
    type: string
