title: microsoftAuthenticatorFeatureSettings
required:
  - '@odata.type'
type: object
properties:
  displayAppInformationRequiredState:
    anyOf:
      - $ref: .\microsoft.graph.authenticationMethodFeatureConfiguration.yaml
      - type: object
        nullable: true
    description: >-
      Determines whether the user's Authenticator app shows them the client app
      they're signing into.
  displayLocationInformationRequiredState:
    anyOf:
      - $ref: .\microsoft.graph.authenticationMethodFeatureConfiguration.yaml
      - type: object
        nullable: true
    description: >-
      Determines whether the user's Authenticator app shows them the geographic
      location of where the authentication request originated from.
  '@odata.type':
    type: string
