allOf:
  - $ref: .\microsoft.graph.customExtensionEndpointConfiguration.yaml
  - title: logicAppTriggerEndpointConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      logicAppWorkflowName:
        type: string
        description: The name of the logic app.
        nullable: true
      resourceGroupName:
        type: string
        description: The Azure resource group name for the logic app.
        nullable: true
      subscriptionId:
        type: string
        description: Identifier of the Azure subscription for the logic app.
        nullable: true
      url:
        type: string
        description: >-
          The URL to the logic app endpoint that will be triggered. Only
          required for app-only token scenarios where app is creating a
          customCalloutExtension without a signed-in user.
        nullable: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.logicAppTriggerEndpointConfiguration'
x-ms-discriminator-value: '#microsoft.graph.logicAppTriggerEndpointConfiguration'
