allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: fieldValueSet
    required:
      - '@odata.type'
    type: object
    properties:
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.fieldValueSet'
