allOf:
  - $ref: .\microsoft.graph.deviceConfiguration.yaml
  - title: windowsPhone81GeneralConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      applyOnlyToWindowsPhone81:
        type: boolean
        description: >-
          Value indicating whether this policy only applies to Windows Phone
          8.1. This property is read-only.
        readOnly: true
      appsBlockCopyPaste:
        type: boolean
        description: Indicates whether or not to block copy paste.
      bluetoothBlocked:
        type: boolean
        description: Indicates whether or not to block bluetooth.
      cameraBlocked:
        type: boolean
        description: Indicates whether or not to block camera.
      cellularBlockWifiTethering:
        type: boolean
        description: >-
          Indicates whether or not to block Wi-Fi tethering. Has no impact if
          Wi-Fi is blocked.
      compliantAppListType:
        $ref: .\microsoft.graph.appListType.yaml
      compliantAppsList:
        type: array
        items:
          $ref: .\microsoft.graph.appListItem.yaml
        description: >-
          List of apps in the compliance (either allow list or block list,
          controlled by CompliantAppListType). This collection can contain a
          maximum of 10000 elements.
      diagnosticDataBlockSubmission:
        type: boolean
        description: Indicates whether or not to block diagnostic data submission.
      emailBlockAddingAccounts:
        type: boolean
        description: Indicates whether or not to block custom email accounts.
      locationServicesBlocked:
        type: boolean
        description: Indicates whether or not to block location services.
      microsoftAccountBlocked:
        type: boolean
        description: Indicates whether or not to block using a Microsoft Account.
      nfcBlocked:
        type: boolean
        description: Indicates whether or not to block Near-Field Communication.
      passwordBlockSimple:
        type: boolean
        description: Indicates whether or not to block syncing the calendar.
      passwordExpirationDays:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Number of days before the password expires.
        format: int32
        nullable: true
      passwordMinimumCharacterSetCount:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Number of character sets a password must contain.
        format: int32
        nullable: true
      passwordMinimumLength:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Minimum length of passwords.
        format: int32
        nullable: true
      passwordMinutesOfInactivityBeforeScreenTimeout:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Minutes of inactivity before screen timeout.
        format: int32
        nullable: true
      passwordPreviousPasswordBlockCount:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Number of previous passwords to block. Valid values 0 to 24
        format: int32
        nullable: true
      passwordRequired:
        type: boolean
        description: Indicates whether or not to require a password.
      passwordRequiredType:
        $ref: .\microsoft.graph.requiredPasswordType.yaml
      passwordSignInFailureCountBeforeFactoryReset:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Number of sign in failures allowed before factory reset.
        format: int32
        nullable: true
      screenCaptureBlocked:
        type: boolean
        description: Indicates whether or not to block screenshots.
      storageBlockRemovableStorage:
        type: boolean
        description: Indicates whether or not to block removable storage.
      storageRequireEncryption:
        type: boolean
        description: Indicates whether or not to require encryption.
      webBrowserBlocked:
        type: boolean
        description: Indicates whether or not to block the web browser.
      wifiBlockAutomaticConnectHotspots:
        type: boolean
        description: >-
          Indicates whether or not to block automatically connecting to Wi-Fi
          hotspots. Has no impact if Wi-Fi is blocked.
      wifiBlocked:
        type: boolean
        description: Indicates whether or not to block Wi-Fi.
      wifiBlockHotspotReporting:
        type: boolean
        description: >-
          Indicates whether or not to block Wi-Fi hotspot reporting. Has no
          impact if Wi-Fi is blocked.
      windowsStoreBlocked:
        type: boolean
        description: Indicates whether or not to block the Windows Store.
      '@odata.type':
        type: string
        default: '#microsoft.graph.windowsPhone81GeneralConfiguration'
    description: >-
      This topic provides descriptions of the declared methods, properties and
      relationships exposed by the windowsPhone81GeneralConfiguration resource.
x-ms-discriminator-value: '#microsoft.graph.windowsPhone81GeneralConfiguration'
