title: crossTenantAccessPolicyConfigurationPartner
required:
  - '@odata.type'
type: object
properties:
  automaticUserConsentSettings:
    anyOf:
      - $ref: .\microsoft.graph.inboundOutboundPolicyConfiguration.yaml
      - type: object
        nullable: true
    description: >-
      Determines the partner-specific configuration for automatic user consent
      settings. Unless specifically configured, the inboundAllowed and
      outboundAllowed properties are null and inherit from the default settings,
      which is always false.
  b2bCollaborationInbound:
    anyOf:
      - $ref: .\microsoft.graph.crossTenantAccessPolicyB2BSetting.yaml
      - type: object
        nullable: true
    description: >-
      Defines your partner-specific configuration for users from other
      organizations accessing your resources via Microsoft Entra B2B
      collaboration.
  b2bCollaborationOutbound:
    anyOf:
      - $ref: .\microsoft.graph.crossTenantAccessPolicyB2BSetting.yaml
      - type: object
        nullable: true
    description: >-
      Defines your partner-specific configuration for users in your organization
      going outbound to access resources in another organization via Microsoft
      Entra B2B collaboration.
  b2bDirectConnectInbound:
    anyOf:
      - $ref: .\microsoft.graph.crossTenantAccessPolicyB2BSetting.yaml
      - type: object
        nullable: true
    description: >-
      Defines your partner-specific configuration for users from other
      organizations accessing your resources via Azure B2B direct connect.
  b2bDirectConnectOutbound:
    anyOf:
      - $ref: .\microsoft.graph.crossTenantAccessPolicyB2BSetting.yaml
      - type: object
        nullable: true
    description: >-
      Defines your partner-specific configuration for users in your organization
      going outbound to access resources in another organization via Microsoft
      Entra B2B direct connect.
  inboundTrust:
    anyOf:
      - $ref: .\microsoft.graph.crossTenantAccessPolicyInboundTrust.yaml
      - type: object
        nullable: true
    description: >-
      Determines the partner-specific configuration for trusting other
      Conditional Access claims from external Microsoft Entra organizations.
  isInMultiTenantOrganization:
    type: boolean
    description: Identifies whether a tenant is a member of a multitenant organization.
    nullable: true
  isServiceProvider:
    type: boolean
    description: >-
      Identifies whether the partner-specific configuration is a Cloud Service
      Provider for your organization.
    nullable: true
  tenantId:
    type: string
    description: >-
      The tenant identifier for the partner Microsoft Entra organization.
      Read-only. Key.
  tenantRestrictions:
    anyOf:
      - $ref: .\microsoft.graph.crossTenantAccessPolicyTenantRestrictions.yaml
      - type: object
        nullable: true
    description: >-
      Defines the partner-specific tenant restrictions configuration for users
      in your organization who access a partner organization using partner
      supplied identities on your network or devices.
  identitySynchronization:
    anyOf:
      - $ref: .\microsoft.graph.crossTenantIdentitySyncPolicyPartner.yaml
      - type: object
        nullable: true
    description: >-
      Defines the cross-tenant policy for the synchronization of users from a
      partner tenant. Use this user synchronization policy to streamline
      collaboration between users in a multitenant organization by automating
      the creation, update, and deletion of users from one tenant to another.
    x-ms-navigationProperty: true
  '@odata.type':
    type: string
