allOf:
  - $ref: .\microsoft.graph.deviceConfiguration.yaml
  - title: windowsPhone81CustomConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      omaSettings:
        type: array
        items:
          $ref: .\microsoft.graph.omaSetting.yaml
        description: OMA settings. This collection can contain a maximum of 1000 elements.
      '@odata.type':
        type: string
        default: '#microsoft.graph.windowsPhone81CustomConfiguration'
    description: >-
      This topic provides descriptions of the declared methods, properties and
      relationships exposed by the windowsPhone81CustomConfiguration resource.
x-ms-discriminator-value: '#microsoft.graph.windowsPhone81CustomConfiguration'
