allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: crossTenantAccessPolicyConfigurationDefault
    required:
      - '@odata.type'
    type: object
    properties:
      automaticUserConsentSettings:
        anyOf:
          - $ref: .\microsoft.graph.inboundOutboundPolicyConfiguration.yaml
          - type: object
            nullable: true
        description: >-
          Determines the default configuration for automatic user consent
          settings. The inboundAllowed and outboundAllowed properties are always
          false and can't be updated in the default configuration. Read-only.
      b2bCollaborationInbound:
        anyOf:
          - $ref: .\microsoft.graph.crossTenantAccessPolicyB2BSetting.yaml
          - type: object
            nullable: true
        description: >-
          Defines your default configuration for users from other organizations
          accessing your resources via Microsoft Entra B2B collaboration.
      b2bCollaborationOutbound:
        anyOf:
          - $ref: .\microsoft.graph.crossTenantAccessPolicyB2BSetting.yaml
          - type: object
            nullable: true
        description: >-
          Defines your default configuration for users in your organization
          going outbound to access resources in another organization via
          Microsoft Entra B2B collaboration.
      b2bDirectConnectInbound:
        anyOf:
          - $ref: .\microsoft.graph.crossTenantAccessPolicyB2BSetting.yaml
          - type: object
            nullable: true
        description: >-
          Defines your default configuration for users from other organizations
          accessing your resources via Microsoft Entra B2B direct connect.
      b2bDirectConnectOutbound:
        anyOf:
          - $ref: .\microsoft.graph.crossTenantAccessPolicyB2BSetting.yaml
          - type: object
            nullable: true
        description: >-
          Defines your default configuration for users in your organization
          going outbound to access resources in another organization via
          Microsoft Entra B2B direct connect.
      inboundTrust:
        anyOf:
          - $ref: .\microsoft.graph.crossTenantAccessPolicyInboundTrust.yaml
          - type: object
            nullable: true
        description: >-
          Determines the default configuration for trusting other Conditional
          Access claims from external Microsoft Entra organizations.
      invitationRedemptionIdentityProviderConfiguration:
        anyOf:
          - $ref: >-
              .\microsoft.graph.defaultInvitationRedemptionIdentityProviderConfiguration.yaml
          - type: object
            nullable: true
        description: >-
          Defines the priority order based on which an identity provider is
          selected during invitation redemption for a guest user.
      isServiceDefault:
        type: boolean
        description: >-
          If true, the default configuration is set to the system default
          configuration. If false, the default settings are customized.
        nullable: true
      tenantRestrictions:
        anyOf:
          - $ref: .\microsoft.graph.crossTenantAccessPolicyTenantRestrictions.yaml
          - type: object
            nullable: true
        description: >-
          Defines the default tenant restrictions configuration for users in
          your organization who access an external organization on your network
          or devices.
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.crossTenantAccessPolicyConfigurationDefault'
