title: customExtensionClientConfiguration
required:
  - '@odata.type'
type: object
properties:
  maximumRetries:
    maximum: 2147483647
    minimum: -2147483648
    type: number
    description: >-
      The max number of retries that Microsoft Entra ID makes to the external
      API. Values of 0 or 1 are supported. If null, the default for the service
      applies.
    format: int32
    nullable: true
  timeoutInMilliseconds:
    maximum: 2147483647
    minimum: -2147483648
    type: number
    description: >-
      The max duration in milliseconds that Microsoft Entra ID waits for a
      response from the external app before it shuts down the connection. The
      valid range is between 200 and 2000 milliseconds. Default duration is
      1000.
    format: int32
    nullable: true
  '@odata.type':
    type: string
