title: ocrSettings
required:
  - '@odata.type'
type: object
properties:
  isEnabled:
    type: boolean
    description: Indicates whether or not OCR is enabled for the case.
    nullable: true
  maxImageSize:
    maximum: 2147483647
    minimum: -2147483648
    type: number
    description: Maximum image size that will be processed in KB).
    format: int32
    nullable: true
  timeout:
    pattern: ^-?P([0-9]+D)?(T([0-9]+H)?([0-9]+M)?([0-9]+([.][0-9]+)?S)?)?$
    type: string
    description: >-
      The timeout duration for the OCR engine. A longer timeout might increase
      success of OCR, but might add to the total processing time.
    format: duration
    nullable: true
  '@odata.type':
    type: string
