title: accessPackageAutomaticRequestSettings
required:
  - '@odata.type'
type: object
properties:
  gracePeriodBeforeAccessRemoval:
    pattern: ^-?P([0-9]+D)?(T([0-9]+H)?([0-9]+M)?([0-9]+([.][0-9]+)?S)?)?$
    type: string
    description: >-
      The duration for which access must be retained before the target's access
      is revoked once they leave the allowed target scope.
    format: duration
    nullable: true
  removeAccessWhenTargetLeavesAllowedTargets:
    type: boolean
    description: >-
      Indicates whether automatic assignment must be removed for targets who
      move out of the allowed target scope.
    nullable: true
  requestAccessForAllowedTargets:
    type: boolean
    description: >-
      If set to true, automatic assignments will be created for targets in the
      allowed target scope.
    nullable: true
  '@odata.type':
    type: string
