title: Collection of x509CertificateCombinationConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.x509CertificateCombinationConfiguration.yaml
