title: Collection of emailAuthenticationMethodConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.emailAuthenticationMethodConfiguration.yaml
