allOf:
  - $ref: .\microsoft.graph.authenticationMethodConfiguration.yaml
  - title: fido2AuthenticationMethodConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      isAttestationEnforced:
        type: boolean
        description: >-
          Determines whether attestation must be enforced for FIDO2 security key
          registration.
        nullable: true
      isSelfServiceRegistrationAllowed:
        type: boolean
        description: Determines if users can register new FIDO2 security keys.
        nullable: true
      keyRestrictions:
        anyOf:
          - $ref: .\microsoft.graph.fido2KeyRestrictions.yaml
          - type: object
            nullable: true
        description: >-
          Controls whether key restrictions are enforced on FIDO2 security keys,
          either allowing or disallowing certain key types as defined by
          Authenticator Attestation GUID (AAGUID), an identifier that indicates
          the type (e.g. make and model) of the authenticator.
      includeTargets:
        type: array
        items:
          $ref: .\microsoft.graph.authenticationMethodTarget.yaml
        description: >-
          A collection of groups that are enabled to use the authentication
          method.
        x-ms-navigationProperty: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.fido2AuthenticationMethodConfiguration'
x-ms-discriminator-value: '#microsoft.graph.fido2AuthenticationMethodConfiguration'
