allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: managedDeviceMobileAppConfigurationUserStatus
    required:
      - '@odata.type'
    type: object
    properties:
      devicesCount:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Devices count for that user.
        format: int32
      lastReportedDateTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: Last modified date time of the policy report.
        format: date-time
      status:
        $ref: .\microsoft.graph.complianceStatus.yaml
      userDisplayName:
        type: string
        description: User name of the DevicePolicyStatus.
        nullable: true
      userPrincipalName:
        type: string
        description: UserPrincipalName.
        nullable: true
      '@odata.type':
        type: string
    description: >-
      Contains properties, inherited properties and actions for an MDM mobile
      app configuration status for a user.
x-ms-discriminator-value: '#microsoft.graph.managedDeviceMobileAppConfigurationUserStatus'
