title: authenticationConditionsApplications
required:
  - '@odata.type'
type: object
properties:
  includeApplications:
    type: array
    items:
      $ref: .\microsoft.graph.authenticationConditionApplication.yaml
    x-ms-navigationProperty: true
  '@odata.type':
    type: string
