allOf:
  - $ref: .\microsoft.graph.subjectSet.yaml
  - title: targetApplicationOwners
    required:
      - '@odata.type'
    type: object
    properties:
      '@odata.type':
        type: string
        default: '#microsoft.graph.targetApplicationOwners'
x-ms-discriminator-value: '#microsoft.graph.targetApplicationOwners'
