title: fileStorageContainerSettings
required:
  - '@odata.type'
type: object
properties:
  isOcrEnabled:
    type: boolean
    description: >-
      Indicates whether Optical Character Recognition (OCR) is enabled for the
      container. The default value is false. When set to true, OCR extraction is
      performed for new and updated documents of supported document types, and
      the extracted fields in the metadata of the document enable end-user
      search and search-driven solutions. When set to false, existing OCR
      metadata is not impacted. Optional. Read-write.
    nullable: true
  '@odata.type':
    type: string
