allOf:
  - $ref: .\microsoft.graph.accessReviewRecommendationInsightSetting.yaml
  - title: groupPeerOutlierRecommendationInsightSettings
    required:
      - '@odata.type'
    type: object
    properties:
      '@odata.type':
        type: string
        default: '#microsoft.graph.groupPeerOutlierRecommendationInsightSettings'
x-ms-discriminator-value: '#microsoft.graph.groupPeerOutlierRecommendationInsightSettings'
