title: loginPageTextVisibilitySettings
required:
  - '@odata.type'
type: object
properties:
  hideAccountResetCredentials:
    type: boolean
    description: >-
      Option to hide the self-service password reset (SSPR) hyperlinks such as
      'Can't access your account?', 'Forgot my password' and 'Reset it now' on
      the sign-in form.
    nullable: true
  hideCannotAccessYourAccount:
    type: boolean
    description: >-
      Option to hide the self-service password reset (SSPR) 'Can't access your
      account?' hyperlink on the sign-in form.
    nullable: true
  hideForgotMyPassword:
    type: boolean
    description: >-
      Option to hide the self-service password reset (SSPR) 'Forgot my password'
      hyperlink on the sign-in form.
    nullable: true
  hidePrivacyAndCookies:
    type: boolean
    description: Option to hide the 'Privacy & Cookies' hyperlink in the footer.
    nullable: true
  hideResetItNow:
    type: boolean
    description: >-
      Option to hide the self-service password reset (SSPR) 'reset it now'
      hyperlink on the sign-in form.
    nullable: true
  hideTermsOfUse:
    type: boolean
    description: Option to hide the 'Terms of Use' hyperlink in the footer.
    nullable: true
  '@odata.type':
    type: string
