title: customExtensionCallbackConfiguration
required:
  - '@odata.type'
type: object
properties:
  timeoutDuration:
    pattern: ^-?P([0-9]+D)?(T([0-9]+H)?([0-9]+M)?([0-9]+([.][0-9]+)?S)?)?$
    type: string
    description: >-
      The maximum duration in ISO 8601 format that Microsoft Entra ID will wait
      for a resume action for the callout it sent to the logic app. The valid
      range for custom extensions in lifecycle workflows is five minutes to
      three hours. The valid range for custom extensions in entitlement
      management is between 5 minutes and 14 days. For example, PT3H refers to
      three hours, P3D refers to three days, PT10M refers to ten minutes.
    format: duration
    nullable: true
  '@odata.type':
    type: string
discriminator:
  propertyName: '@odata.type'
  mapping:
    '#microsoft.graph.identityGovernance.customTaskExtensionCallbackConfiguration': >-
      .\microsoft.graph.identityGovernance.customTaskExtensionCallbackConfiguration.yaml
    microsoft.graph.identityGovernance.customTaskExtensionCallbackConfiguration: >-
      .\microsoft.graph.identityGovernance.customTaskExtensionCallbackConfiguration.yaml
