title: Collection of microsoftAuthenticatorAuthenticationMethodConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: >-
            .\microsoft.graph.microsoftAuthenticatorAuthenticationMethodConfiguration.yaml
