allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: adminReportSettings
    required:
      - '@odata.type'
    type: object
    properties:
      displayConcealedNames:
        type: boolean
        description: >-
          If set to true, all reports conceal user information such as
          usernames, groups, and sites. If false, all reports show identifiable
          information. This property represents a setting in the Microsoft 365
          admin center. Required.
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.adminReportSettings'
