title: Collection of windows10SecureAssessmentConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: .\microsoft.graph.windows10SecureAssessmentConfiguration.yaml
