description: Retrieved collection
content:
  application/json:
    schema:
      $ref: >-
        ..\schemas\microsoft.graph.windowsDefenderAdvancedThreatProtectionConfigurationCollectionResponse.yaml
