title: browserSharedCookieSourceEnvironment
enum:
  - microsoftEdge
  - internetExplorer11
  - both
  - unknownFutureValue
type: string
x-ms-enum:
  name: browserSharedCookieSourceEnvironment
  modelAsString: false
  values:
    - value: microsoftEdge
      description: Share session cookies from Microsoft Edge to Internet Explorer.
      name: microsoftEdge
    - value: internetExplorer11
      description: Share session cookies from Internet Explorer to Microsoft Edge.
      name: internetExplorer11
    - value: both
      description: Share session cookies to and from Microsoft Edge and Internet Explorer.
      name: both
    - value: unknownFutureValue
      description: >-
        Placeholder for evolvable enum, but this enum is never returned to the
        caller, so it shouldn't be necessary.
      name: unknownFutureValue
