title: bookingPageSettings
required:
  - '@odata.type'
type: object
properties:
  accessControl:
    $ref: .\microsoft.graph.bookingPageAccessControl.yaml
  bookingPageColorCode:
    type: string
    description: >-
      Custom color for the booking page. The value should be in Hex format. For
      example, #123456.
  businessTimeZone:
    type: string
    description: >-
      The time zone of the customer. For a list of possible values, see
      dateTimeTimeZone.
  customerConsentMessage:
    type: string
    description: >-
      The personal data collection and usage consent message in the booking
      page.
  enforceOneTimePassword:
    type: boolean
    description: >-
      Determines whether the one-time password is required to create an
      appointment. The default value is false.
  isBusinessLogoDisplayEnabled:
    type: boolean
    description: >-
      Indicates whether the business logo is displayed on the booking page. The
      default value is false.
  isCustomerConsentEnabled:
    type: boolean
    description: >-
      Enables personal data collection and the usage consent toggle on the
      booking page. The default value is false.
  isSearchEngineIndexabilityDisabled:
    type: boolean
    description: >-
      Indicates whether web crawlers index this page. The defaults value is
      false.
  isTimeSlotTimeZoneSetToBusinessTimeZone:
    type: boolean
    description: >-
      Indicates whether the time zone of the time slot is set to the time zone
      of the business. The default value is false.
  privacyPolicyWebUrl:
    type: string
    description: >-
      URL of a webpage that provides the terms and conditions of the business.
      If a privacy policy isn't included, the following text appears on the
      booking page as default: 'The policies and practices of
      {bookingbusinessname} apply to the use of your data.'
  termsAndConditionsWebUrl:
    type: string
    description: URL of a webpage that provides the terms and conditions of the business.
  '@odata.type':
    type: string
