title: passwordCredentialConfiguration
required:
  - '@odata.type'
type: object
properties:
  maxLifetime:
    pattern: ^-?P([0-9]+D)?(T([0-9]+H)?([0-9]+M)?([0-9]+([.][0-9]+)?S)?)?$
    type: string
    description: >-
      String value that indicates the maximum lifetime for password expiration,
      defined as an ISO 8601 duration. For example, P4DT12H30M5S represents four
      days, 12 hours, 30 minutes, and five seconds. This property is required
      when restrictionType is set to passwordLifetime.
    format: duration
    nullable: true
  restrictForAppsCreatedAfterDateTime:
    pattern: >-
      ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
    type: string
    description: >-
      Specifies the date from which the policy restriction applies to newly
      created applications. For existing applications, the enforcement date can
      be retroactively applied.
    format: date-time
    nullable: true
  restrictionType:
    anyOf:
      - $ref: .\microsoft.graph.appCredentialRestrictionType.yaml
      - type: object
        nullable: true
    description: >-
      The type of restriction being applied. The possible values are:
      passwordAddition, passwordLifetime, symmetricKeyAddition,
      symmetricKeyLifetime, customPasswordAddition, and unknownFutureValue. Each
      value of restrictionType can be used only once per policy.
  '@odata.type':
    type: string
