allOf:
  - $ref: .\microsoft.graph.mobileAppAssignmentSettings.yaml
  - title: macOsLobAppAssignmentSettings
    required:
      - '@odata.type'
    type: object
    properties:
      uninstallOnDeviceRemoval:
        type: boolean
        description: >-
          When TRUE, indicates that the app should be uninstalled when the
          device is removed from Intune. When FALSE, indicates that the app will
          not be uninstalled when the device is removed from Intune.
        nullable: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.macOsLobAppAssignmentSettings'
    description: Contains properties used to assign a macOS LOB app to a group.
x-ms-discriminator-value: '#microsoft.graph.macOsLobAppAssignmentSettings'
