allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: iosLobAppProvisioningConfigurationAssignment
    required:
      - '@odata.type'
    type: object
    properties:
      target:
        anyOf:
          - $ref: .\microsoft.graph.deviceAndAppManagementAssignmentTarget.yaml
          - type: object
            nullable: true
        description: The target group assignment defined by the admin.
      '@odata.type':
        type: string
    description: >-
      A class containing the properties used for Group Assignment of an iOS LOB
      App Provisioning and Configuration.
x-ms-discriminator-value: '#microsoft.graph.iosLobAppProvisioningConfigurationAssignment'
