title: authenticationAttributeCollectionOptionConfiguration
required:
  - '@odata.type'
type: object
properties:
  label:
    type: string
    description: The label of the option that will be displayed to user, unless overridden.
  value:
    type: string
    description: The value of the option that will be stored.
  '@odata.type':
    type: string
