allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: userSettings
    required:
      - '@odata.type'
    type: object
    properties:
      contributionToContentDiscoveryAsOrganizationDisabled:
        type: boolean
        description: >-
          Reflects the organization level setting controlling delegate access to
          the trending API. When set to true, the organization doesn't have
          access to Office Delve. The relevancy of the content displayed in
          Microsoft 365, for example in Suggested sites in SharePoint Home and
          the Discover view in OneDrive for work or school is affected for the
          whole organization. This setting is read-only and can only be changed
          by administrators in the SharePoint admin center.
      contributionToContentDiscoveryDisabled:
        type: boolean
        description: >-
          When set to true, the delegate access to the user's trending API is
          disabled. When set to true, documents in the user's Office Delve are
          disabled. When set to true, the relevancy of the content displayed in
          Microsoft 365, for example in Suggested sites in SharePoint Home and
          the Discover view in OneDrive for work or school is affected. Users
          can control this setting in Office Delve.
      itemInsights:
        anyOf:
          - $ref: .\microsoft.graph.userInsightsSettings.yaml
          - type: object
            nullable: true
        description: >-
          The user's settings for the visibility of meeting hour insights, and
          insights derived between a user and other items in Microsoft 365, such
          as documents or sites. Get userInsightsSettings through this
          navigation property.
        x-ms-navigationProperty: true
      shiftPreferences:
        anyOf:
          - $ref: .\microsoft.graph.shiftPreferences.yaml
          - type: object
            nullable: true
        x-ms-navigationProperty: true
      storage:
        anyOf:
          - $ref: .\microsoft.graph.userStorage.yaml
          - type: object
            nullable: true
        x-ms-navigationProperty: true
      windows:
        type: array
        items:
          $ref: .\microsoft.graph.windowsSetting.yaml
        x-ms-navigationProperty: true
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.userSettings'
