title: accessPackageAssignmentReviewSettings
required:
  - '@odata.type'
type: object
properties:
  expirationBehavior:
    anyOf:
      - $ref: .\microsoft.graph.accessReviewExpirationBehavior.yaml
      - type: object
        nullable: true
    description: >-
      The default decision to apply if the access is not reviewed. The possible
      values are: keepAccess, removeAccess, acceptAccessRecommendation,
      unknownFutureValue.
  fallbackReviewers:
    type: array
    items:
      $ref: .\microsoft.graph.subjectSet.yaml
    description: >-
      This collection specifies the users who will be the fallback reviewers
      when the primary reviewers don't respond.
  isEnabled:
    type: boolean
    description: If true, access reviews are required for assignments through this policy.
    nullable: true
  isRecommendationEnabled:
    type: boolean
    description: >-
      Specifies whether to display recommendations to the reviewer. The default
      value is true.
    nullable: true
  isReviewerJustificationRequired:
    type: boolean
    description: >-
      Specifies whether the reviewer must provide justification for the
      approval. The default value is true.
    nullable: true
  isSelfReview:
    type: boolean
    description: Specifies whether the principals can review their own assignments.
    nullable: true
  primaryReviewers:
    type: array
    items:
      $ref: .\microsoft.graph.subjectSet.yaml
    description: >-
      This collection specifies the users or group of users who will review the
      access package assignments.
  schedule:
    anyOf:
      - $ref: .\microsoft.graph.entitlementManagementSchedule.yaml
      - type: object
        nullable: true
    description: When the first review should start and how often it should recur.
  '@odata.type':
    type: string
