title: configuration
required:
  - '@odata.type'
type: object
properties:
  authorizedAppIds:
    type: array
    items:
      type: string
      nullable: true
    description: >-
      A collection of application IDs for registered Microsoft Entra apps that
      are allowed to manage the externalConnection and to index content in the
      externalConnection.
  '@odata.type':
    type: string
