allOf:
  - $ref: .\microsoft.graph.mobileAppAssignmentSettings.yaml
  - title: windowsUniversalAppXAppAssignmentSettings
    required:
      - '@odata.type'
    type: object
    properties:
      useDeviceContext:
        type: boolean
        description: >-
          If true, uses device execution context for Windows Universal AppX
          mobile app. Device-context install is not allowed when this type of
          app is targeted with Available intent. Defaults to false.
      '@odata.type':
        type: string
        default: '#microsoft.graph.windowsUniversalAppXAppAssignmentSettings'
    description: >-
      Contains properties used when assigning a Windows Universal AppX mobile
      app to a group.
x-ms-discriminator-value: '#microsoft.graph.windowsUniversalAppXAppAssignmentSettings'
