allOf:
  - $ref: .\microsoft.graph.deviceConfiguration.yaml
  - title: androidGeneralDeviceConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      appsBlockClipboardSharing:
        type: boolean
        description: >-
          Indicates whether or not to block clipboard sharing to copy and paste
          between applications.
      appsBlockCopyPaste:
        type: boolean
        description: Indicates whether or not to block copy and paste within applications.
      appsBlockYouTube:
        type: boolean
        description: Indicates whether or not to block the YouTube app.
      appsHideList:
        type: array
        items:
          $ref: .\microsoft.graph.appListItem.yaml
        description: >-
          List of apps to be hidden on the KNOX device. This collection can
          contain a maximum of 500 elements.
      appsInstallAllowList:
        type: array
        items:
          $ref: .\microsoft.graph.appListItem.yaml
        description: >-
          List of apps which can be installed on the KNOX device. This
          collection can contain a maximum of 500 elements.
      appsLaunchBlockList:
        type: array
        items:
          $ref: .\microsoft.graph.appListItem.yaml
        description: >-
          List of apps which are blocked from being launched on the KNOX device.
          This collection can contain a maximum of 500 elements.
      bluetoothBlocked:
        type: boolean
        description: Indicates whether or not to block Bluetooth.
      cameraBlocked:
        type: boolean
        description: Indicates whether or not to block the use of the camera.
      cellularBlockDataRoaming:
        type: boolean
        description: Indicates whether or not to block data roaming.
      cellularBlockMessaging:
        type: boolean
        description: Indicates whether or not to block SMS/MMS messaging.
      cellularBlockVoiceRoaming:
        type: boolean
        description: Indicates whether or not to block voice roaming.
      cellularBlockWiFiTethering:
        type: boolean
        description: Indicates whether or not to block syncing Wi-Fi tethering.
      compliantAppListType:
        $ref: .\microsoft.graph.appListType.yaml
      compliantAppsList:
        type: array
        items:
          $ref: .\microsoft.graph.appListItem.yaml
        description: >-
          List of apps in the compliance (either allow list or block list,
          controlled by CompliantAppListType). This collection can contain a
          maximum of 10000 elements.
      deviceSharingAllowed:
        type: boolean
        description: Indicates whether or not to allow device sharing mode.
      diagnosticDataBlockSubmission:
        type: boolean
        description: Indicates whether or not to block diagnostic data submission.
      factoryResetBlocked:
        type: boolean
        description: Indicates whether or not to block user performing a factory reset.
      googleAccountBlockAutoSync:
        type: boolean
        description: Indicates whether or not to block Google account auto sync.
      googlePlayStoreBlocked:
        type: boolean
        description: Indicates whether or not to block the Google Play store.
      kioskModeApps:
        type: array
        items:
          $ref: .\microsoft.graph.appListItem.yaml
        description: >-
          A list of apps that will be allowed to run when the device is in Kiosk
          Mode. This collection can contain a maximum of 500 elements.
      kioskModeBlockSleepButton:
        type: boolean
        description: >-
          Indicates whether or not to block the screen sleep button while in
          Kiosk Mode.
      kioskModeBlockVolumeButtons:
        type: boolean
        description: >-
          Indicates whether or not to block the volume buttons while in Kiosk
          Mode.
      locationServicesBlocked:
        type: boolean
        description: Indicates whether or not to block location services.
      nfcBlocked:
        type: boolean
        description: Indicates whether or not to block Near-Field Communication.
      passwordBlockFingerprintUnlock:
        type: boolean
        description: Indicates whether or not to block fingerprint unlock.
      passwordBlockTrustAgents:
        type: boolean
        description: Indicates whether or not to block Smart Lock and other trust agents.
      passwordExpirationDays:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Number of days before the password expires. Valid values 1 to 365
        format: int32
        nullable: true
      passwordMinimumLength:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Minimum length of passwords. Valid values 4 to 16
        format: int32
        nullable: true
      passwordMinutesOfInactivityBeforeScreenTimeout:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Minutes of inactivity before the screen times out.
        format: int32
        nullable: true
      passwordPreviousPasswordBlockCount:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: Number of previous passwords to block. Valid values 0 to 24
        format: int32
        nullable: true
      passwordRequired:
        type: boolean
        description: Indicates whether or not to require a password.
      passwordRequiredType:
        $ref: .\microsoft.graph.androidRequiredPasswordType.yaml
      passwordSignInFailureCountBeforeFactoryReset:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: >-
          Number of sign in failures allowed before factory reset. Valid values
          1 to 16
        format: int32
        nullable: true
      powerOffBlocked:
        type: boolean
        description: Indicates whether or not to block powering off the device.
      screenCaptureBlocked:
        type: boolean
        description: Indicates whether or not to block screenshots.
      securityRequireVerifyApps:
        type: boolean
        description: Require the Android Verify apps feature is turned on.
      storageBlockGoogleBackup:
        type: boolean
        description: Indicates whether or not to block Google Backup.
      storageBlockRemovableStorage:
        type: boolean
        description: Indicates whether or not to block removable storage usage.
      storageRequireDeviceEncryption:
        type: boolean
        description: Indicates whether or not to require device encryption.
      storageRequireRemovableStorageEncryption:
        type: boolean
        description: Indicates whether or not to require removable storage encryption.
      voiceAssistantBlocked:
        type: boolean
        description: Indicates whether or not to block the use of the Voice Assistant.
      voiceDialingBlocked:
        type: boolean
        description: Indicates whether or not to block voice dialing.
      webBrowserBlockAutofill:
        type: boolean
        description: Indicates whether or not to block the web browser's auto fill feature.
      webBrowserBlocked:
        type: boolean
        description: Indicates whether or not to block the web browser.
      webBrowserBlockJavaScript:
        type: boolean
        description: Indicates whether or not to block JavaScript within the web browser.
      webBrowserBlockPopups:
        type: boolean
        description: Indicates whether or not to block popups within the web browser.
      webBrowserCookieSettings:
        $ref: .\microsoft.graph.webBrowserCookieSettings.yaml
      wiFiBlocked:
        type: boolean
        description: Indicates whether or not to block syncing Wi-Fi.
      '@odata.type':
        type: string
        default: '#microsoft.graph.androidGeneralDeviceConfiguration'
    description: >-
      This topic provides descriptions of the declared methods, properties and
      relationships exposed by the androidGeneralDeviceConfiguration resource.
x-ms-discriminator-value: '#microsoft.graph.androidGeneralDeviceConfiguration'
