title: samlSingleSignOnSettings
required:
  - '@odata.type'
type: object
properties:
  relayState:
    type: string
    description: >-
      The relative URI the service provider would redirect to after completion
      of the single sign-on flow.
    nullable: true
  '@odata.type':
    type: string
