allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: ediscoveryCaseSettings
    required:
      - '@odata.type'
    type: object
    properties:
      ocr:
        anyOf:
          - $ref: .\microsoft.graph.security.ocrSettings.yaml
          - type: object
            nullable: true
        description: The OCR (Optical Character Recognition) settings for the case.
      redundancyDetection:
        anyOf:
          - $ref: .\microsoft.graph.security.redundancyDetectionSettings.yaml
          - type: object
            nullable: true
        description: >-
          The redundancy (near duplicate and email threading) detection settings
          for the case.
      topicModeling:
        anyOf:
          - $ref: .\microsoft.graph.security.topicModelingSettings.yaml
          - type: object
            nullable: true
        description: The Topic Modeling (Themes) settings for the case.
      '@odata.type':
        type: string
x-ms-discriminator-value: '#microsoft.graph.security.ediscoveryCaseSettings'
