allOf:
  - $ref: .\microsoft.graph.entity.yaml
  - title: deviceComplianceSettingState
    required:
      - '@odata.type'
    type: object
    properties:
      complianceGracePeriodExpirationDateTime:
        pattern: >-
          ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
        type: string
        description: The DateTime when device compliance grace period expires
        format: date-time
      deviceId:
        type: string
        description: The Device Id that is being reported
        nullable: true
      deviceModel:
        type: string
        description: The device model that is being reported
        nullable: true
      deviceName:
        type: string
        description: The Device Name that is being reported
        nullable: true
      setting:
        type: string
        description: The setting class name and property name.
        nullable: true
      settingName:
        type: string
        description: The Setting Name that is being reported
        nullable: true
      state:
        $ref: .\microsoft.graph.complianceStatus.yaml
      userEmail:
        type: string
        description: The User email address that is being reported
        nullable: true
      userId:
        type: string
        description: The user Id that is being reported
        nullable: true
      userName:
        type: string
        description: The User Name that is being reported
        nullable: true
      userPrincipalName:
        type: string
        description: The User PrincipalName that is being reported
        nullable: true
      '@odata.type':
        type: string
    description: Device compliance setting State for a given device.
x-ms-discriminator-value: '#microsoft.graph.deviceComplianceSettingState'
