title: redundancyDetectionSettings
required:
  - '@odata.type'
type: object
properties:
  isEnabled:
    type: boolean
    description: >-
      Indicates whether email threading and near duplicate detection are
      enabled.
    nullable: true
  maxWords:
    maximum: 2147483647
    minimum: -2147483648
    type: number
    description: >-
      Specifies the maximum number of words used for email threading and near
      duplicate detection. To learn more, see Minimum/maximum number of words.
    format: int32
    nullable: true
  minWords:
    maximum: 2147483647
    minimum: -2147483648
    type: number
    description: >-
      Specifies the minimum number of words used for email threading and near
      duplicate detection. To learn more, see Minimum/maximum number of words.
    format: int32
    nullable: true
  similarityThreshold:
    maximum: 2147483647
    minimum: -2147483648
    type: number
    description: >-
      Specifies the similarity level for documents to be put in the same near
      duplicate set. To learn more, see Document and email similarity threshold.
    format: int32
    nullable: true
  '@odata.type':
    type: string
