title: loginPageLayoutConfiguration
required:
  - '@odata.type'
type: object
properties:
  isFooterShown:
    type: boolean
    description: Option to show the footer on the sign-in page.
    nullable: true
  isHeaderShown:
    type: boolean
    description: Option to show the header on the sign-in page.
    nullable: true
  layoutTemplateType:
    anyOf:
      - $ref: .\microsoft.graph.layoutTemplateType.yaml
      - type: object
        nullable: true
    description: >-
      Represents the layout template to be displayed on the login page for a
      tenant. The possible values are  default - Represents the default
      Microsoft layout with a centered lightbox.  verticalSplit - Represents a
      layout with a background on the left side and a full-height lightbox to
      the right.  unknownFutureValue - Evolvable enumeration sentinel value.
      Don't use.
  '@odata.type':
    type: string
