allOf:
  - $ref: .\microsoft.graph.authenticationMethodConfiguration.yaml
  - title: temporaryAccessPassAuthenticationMethodConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      defaultLength:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: >-
          Default length in characters of a Temporary Access Pass object. Must
          be between 8 and 48 characters.
        format: int32
        nullable: true
      defaultLifetimeInMinutes:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: >-
          Default lifetime in minutes for a Temporary Access Pass. Value can be
          any integer between the minimumLifetimeInMinutes and
          maximumLifetimeInMinutes.
        format: int32
        nullable: true
      isUsableOnce:
        type: boolean
        description: >-
          If true, all the passes in the tenant will be restricted to one-time
          use. If false, passes in the tenant can be created to be either
          one-time use or reusable.
        nullable: true
      maximumLifetimeInMinutes:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: >-
          Maximum lifetime in minutes for any Temporary Access Pass created in
          the tenant. Value can be between 10 and 43200 minutes (equivalent to
          30 days).
        format: int32
        nullable: true
      minimumLifetimeInMinutes:
        maximum: 2147483647
        minimum: -2147483648
        type: number
        description: >-
          Minimum lifetime in minutes for any Temporary Access Pass created in
          the tenant. Value can be between 10 and 43200 minutes (equivalent to
          30 days).
        format: int32
        nullable: true
      includeTargets:
        type: array
        items:
          $ref: .\microsoft.graph.authenticationMethodTarget.yaml
        description: >-
          A collection of groups that are enabled to use the authentication
          method.
        x-ms-navigationProperty: true
      '@odata.type':
        type: string
        default: '#microsoft.graph.temporaryAccessPassAuthenticationMethodConfiguration'
x-ms-discriminator-value: '#microsoft.graph.temporaryAccessPassAuthenticationMethodConfiguration'
