title: >-
  Collection of
  microsoft.graph.authenticationAttributeCollectionInputConfiguration
type: object
allOf:
  - $ref: .\BaseCollectionPaginationCountResponse.yaml
  - type: object
    properties:
      value:
        type: array
        items:
          $ref: >-
            .\microsoft.graph.authenticationAttributeCollectionInputConfiguration.yaml
