allOf:
  - $ref: .\microsoft.graph.deviceConfiguration.yaml
  - title: androidWorkProfileCustomConfiguration
    required:
      - '@odata.type'
    type: object
    properties:
      omaSettings:
        type: array
        items:
          $ref: .\microsoft.graph.omaSetting.yaml
        description: OMA settings. This collection can contain a maximum of 500 elements.
      '@odata.type':
        type: string
        default: '#microsoft.graph.androidWorkProfileCustomConfiguration'
    description: Android Work Profile custom configuration
x-ms-discriminator-value: '#microsoft.graph.androidWorkProfileCustomConfiguration'
