value:
  createdBy:
    '@odata.type': microsoft.graph.emailIdentity
  createdDateTime: '0001-01-01T00:00:00.0000000+00:00'
  description: String
  displayName: String
  lastModifiedBy:
    '@odata.type': microsoft.graph.emailIdentity
  lastModifiedDateTime: '0001-01-01T00:00:00.0000000+00:00'
  lastRunDateTime: '0001-01-01T00:00:00.0000000+00:00'
  nextRunDateTime: '0001-01-01T00:00:00.0000000+00:00'
  runs:
    - '@odata.type': microsoft.graph.simulationAutomationRun
  status:
    '@odata.type': microsoft.graph.simulationAutomationStatus
