value:
  assignedDevices:
    - '@odata.type': microsoft.graph.windowsAutopilotDeviceIdentity
  createdDateTime: '0001-01-01T00:00:00.0000000+00:00'
  description: String
  deviceNameTemplate: String
  deviceType:
    '@odata.type': microsoft.graph.windowsAutopilotDeviceType
  displayName: String
  hardwareHashExtractionEnabled: 'true'
  lastModifiedDateTime: '0001-01-01T00:00:00.0000000+00:00'
  locale: String
  managementServiceAppId: String
  outOfBoxExperienceSetting:
    '@odata.type': microsoft.graph.outOfBoxExperienceSetting
  preprovisioningAllowed: 'true'
  roleScopeTagIds:
    - String
