value:
  automaticUserConsentSettings:
    '@odata.type': microsoft.graph.inboundOutboundPolicyConfiguration
  b2bCollaborationInbound:
    '@odata.type': microsoft.graph.crossTenantAccessPolicyB2BSetting
  b2bCollaborationOutbound:
    '@odata.type': microsoft.graph.crossTenantAccessPolicyB2BSetting
  b2bDirectConnectInbound:
    '@odata.type': microsoft.graph.crossTenantAccessPolicyB2BSetting
  b2bDirectConnectOutbound:
    '@odata.type': microsoft.graph.crossTenantAccessPolicyB2BSetting
  inboundTrust:
    '@odata.type': microsoft.graph.crossTenantAccessPolicyInboundTrust
  invitationRedemptionIdentityProviderConfiguration:
    '@odata.type': microsoft.graph.defaultInvitationRedemptionIdentityProviderConfiguration
  isServiceDefault: 'true'
  tenantRestrictions:
    '@odata.type': microsoft.graph.crossTenantAccessPolicyTenantRestrictions
