value:
  maxLifetime: Duration
  restrictForAppsCreatedAfterDateTime: '0001-01-01T00:00:00.0000000+00:00'
  restrictionType:
    '@odata.type': microsoft.graph.appKeyCredentialRestrictionType
  state:
    '@odata.type': microsoft.graph.appManagementRestrictionState
