value:
  applicationFilter:
    '@odata.type': microsoft.graph.conditionalAccessFilter
  excludeApplications:
    - String
  includeApplications:
    - String
  includeAuthenticationContextClassReferences:
    - String
  includeUserActions:
    - String
