value:
  complianceGracePeriodExpirationDateTime: '0001-01-01T00:00:00.0000000+00:00'
  deviceId: String
  deviceModel: String
  deviceName: String
  setting: String
  settingName: String
  state:
    '@odata.type': microsoft.graph.complianceStatus
  userEmail: String
  userId: String
  userName: String
  userPrincipalName: String
