value:
  displayAppInformationRequiredState:
    '@odata.type': microsoft.graph.authenticationMethodFeatureConfiguration
  displayLocationInformationRequiredState:
    '@odata.type': microsoft.graph.authenticationMethodFeatureConfiguration
