value:
  configurationDeployedUserCount: '0'
  configurationDeploymentSummaryPerApp:
    - '@odata.type': microsoft.graph.managedAppPolicyDeploymentSummaryPerApp
  displayName: String
  lastRefreshTime: '0001-01-01T00:00:00.0000000+00:00'
  version: String
