value:
  configurationId: String
  configurationType:
    '@odata.type': microsoft.graph.security.mailboxConfigurationType
  displayName: String
  externalDirectoryObjectId: 00000000-0000-0000-0000-000000000000
  mailboxPrimaryAddress: String
  upn: String
