value:
  accountsBlockAddingNonMicrosoftAccountEmail: 'true'
  applyOnlyToWindows81: 'true'
  browserBlockAutofill: 'true'
  browserBlockAutomaticDetectionOfIntranetSites: 'true'
  browserBlockEnterpriseModeAccess: 'true'
  browserBlockJavaScript: 'true'
  browserBlockPlugins: 'true'
  browserBlockPopups: 'true'
  browserBlockSendingDoNotTrackHeader: 'true'
  browserBlockSingleWordEntryOnIntranetSites: 'true'
  browserEnterpriseModeSiteListLocation: String
  browserInternetSecurityLevel:
    '@odata.type': microsoft.graph.internetSiteSecurityLevel
  browserIntranetSecurityLevel:
    '@odata.type': microsoft.graph.siteSecurityLevel
  browserLoggingReportLocation: String
  browserRequireFirewall: 'true'
  browserRequireFraudWarning: 'true'
  browserRequireHighSecurityForRestrictedSites: 'true'
  browserRequireSmartScreen: 'true'
  browserTrustedSitesSecurityLevel:
    '@odata.type': microsoft.graph.siteSecurityLevel
  cellularBlockDataRoaming: 'true'
  diagnosticsBlockDataSubmission: 'true'
  passwordBlockPicturePasswordAndPin: 'true'
  passwordExpirationDays: '0'
  passwordMinimumCharacterSetCount: '0'
  passwordMinimumLength: '0'
  passwordMinutesOfInactivityBeforeScreenTimeout: '0'
  passwordPreviousPasswordBlockCount: '0'
  passwordRequiredType:
    '@odata.type': microsoft.graph.requiredPasswordType
  passwordSignInFailureCountBeforeFactoryReset: '0'
  storageRequireDeviceEncryption: 'true'
  updatesRequireAutomaticUpdates: 'true'
  userAccountControlSettings:
    '@odata.type': microsoft.graph.windowsUserAccountControlSettings
  workFoldersUrl: String
