value:
  assignments:
    - '@odata.type': microsoft.graph.enrollmentConfigurationAssignment
  createdDateTime: '0001-01-01T00:00:00.0000000+00:00'
  description: String
  displayName: String
  lastModifiedDateTime: '0001-01-01T00:00:00.0000000+00:00'
  priority: '0'
  version: '0'
