value:
  activeDeviceCount: '0'
  appCrashCount: '0'
  appDisplayName: String
  appHangCount: '0'
  appHealthScore: '0'
  appName: String
  appPublisher: String
  appUsageDuration: '0'
  meanTimeToFailureInMinutes: '0'
