value:
  devicesCount: '0'
  lastReportedDateTime: '0001-01-01T00:00:00.0000000+00:00'
  status:
    '@odata.type': microsoft.graph.complianceStatus
  userDisplayName: String
  userPrincipalName: String
